// Questo è il tuo magazzino domande (scrivine quante ne vuoi per livello)
const domandaRepo = {
    Python: {
        L1: [
            "Come stampi Ciao?|print('Ciao')|echo 'Ciao'|console.log('Ciao')|0|In Python si usa print().",
"Come assegni il valore 5 alla variabile x?|x == 5|x = 5|5 -> x|1|In Python si usa = per assegnare valori.",
"Quale tipo di dato è 3.14?|int|str|float|2|3.14 è un numero decimale, quindi float.",
"Come fai un commento in Python?|# Questo è un commento|// Commento|/* Commento */|0|I commenti iniziano con #.",
"Come controlli se x è uguale a 10?|x = 10|x == 10|x === 10|1|Per confrontare valori si usa ==.",
"Come sommi due numeri x e y?|x + y|x add y|x & y|0|In Python l'operatore + somma i numeri.",
"Come sottrai y da x?|x - y|x sub y|x * y|0|L'operatore - sottrae i valori.",
"Come moltiplichi x e y?|x * y|x x y|x . y|0|L'operatore * moltiplica i valori.",
"Come dividi x per y?|x / y|x // y|x % y|0|L'operatore / esegue la divisione.",
"Come fai il resto della divisione di x per y?|x % y|x / y|x // y|0|L'operatore % calcola il modulo.",
"Qual è il risultato di 3 ** 2?|6|9|8|1|** è l'operatore di potenza, 3²=9.",
"Come scrivi una condizione if?|if x > 0:|if(x > 0)|if x > 0 then|0|Python usa if seguito da due punti.",
"Come scrivi un else?|else:|otherwise|else if|0|Si usa else seguito da :.",
"Come scrivi un elif?|elif x == 0:|elseif x == 0|else if x == 0|0|elif è elif, non elseif.",
"Come fai un ciclo for per x in lista?|for x in lista:|for x = lista|for each x in lista|0|Sintassi corretta: for x in lista:",
"Come fai un ciclo while?|while x < 5:|while(x < 5)|do while x < 5|0|while usa i due punti per iniziare il blocco.",
"Come interrompi un ciclo?|break|stop|exit|0|break esce dal ciclo immediatamente.",
"Come salti un’iterazione di un ciclo?|continue|skip|pass|0|continue salta l'iterazione corrente.",
"Come fai nulla in Python?|pass|null|none|0|pass è un'istruzione nulla.",
"Qual è il valore booleano vero?|True|TRUE|1|0|In Python True è booleano vero.",
"Qual è il valore booleano falso?|False|0|Falsey|0|False rappresenta il booleano falso.",
"Come unisci due stringhe 'Ciao' e 'Mondo'?|'Ciao' + 'Mondo'|'Ciao'.concat('Mondo')|'Ciao'.append('Mondo')|0|L’operatore + concatena le stringhe.",
"Come ripeti una stringa 3 volte|'Ciao' * 3|'Ciao'.repeat(3)|'Ciao'.times(3)|0|'Ciao' * 3 = 'CiaoCiaoCiao'.",
"Come trasformi '123' in numero?|int('123')|str('123')|float('123')|0|int() converte la stringa in intero.",
"Come trasformi 123 in stringa?|str(123)|int(123)|format(123)|0|str() converte un numero in stringa.",
"Qual è il risultato di True and False?|True|False|None|1|True and False = False.",
"Qual è il risultato di True or False?|True|False|None|0|True or False = True.",
"Qual è il risultato di not True?|True|False|None|1|not True = False.",
"Come controlli se un elemento è in lista?|x in lista|x exists lista|lista.has(x)|0|in verifica presenza.",
"Come controlli se non è in lista?|x not in lista|x !in lista|x not exists lista|0|not in verifica assenza.",
"Come scarti spazi iniziali e finali di una stringa?|s.strip()|s.trim()|s.clean()|0|strip() rimuove spazi iniziali e finali.",
"Come trasformi una stringa in maiuscolo?|s.upper()|s.toUpperCase()|s.cap()|0|upper() converte in maiuscolo.",
"Come trasformi una stringa in minuscolo?|s.lower()|s.toLowerCase()|s.min()|0|lower() converte in minuscolo.",
"Come dividi una stringa s per spazi?|s.split()|s.divide()|s.cut()|0|split() divide la stringa in lista.",
"Come unisci una lista di stringhe?|''.join(lista)|concat(lista)|merge(lista)|0|join() unisce gli elementi in una stringa.",
"Quale tipo di dato è [1, 2, 3]?|list|tuple|dict|0|Le liste sono delimitate da []",
"Quale tipo di dato è (1, 2, 3)?|tuple|list|set|0|Le tuple sono delimitate da ()",
"Quale tipo di dato è {1, 2, 3}?|set|list|tuple|0|I set sono delimitati da {} senza chiavi",
"Quale tipo di dato è {'a': 1}|dict|list|set|0|Dizionario ha coppie chiave:valore.",
"Come elimini un elemento da una lista?|lista.remove(x)|lista.delete(x)|del lista[x]|0|remove() rimuove un valore specifico."
            // Aggiungi qui le altre 97 domande seguendo lo schema
        ],
        L2: ["Come aggiungi un elemento a una lista chiamata lista?|lista.append(5)|lista.add(5)|lista.push(5)|0|In Python si usa append() per aggiungere elementi a una lista.",
"Come ottieni la lunghezza di una lista?|len(lista)|lista.length|lista.size|0|len() restituisce il numero di elementi.",
"Come gestisci un errore in Python?|try/except|catch|error handling|0|Il blocco try/except cattura le eccezioni.",
"Come estrai il primo elemento di una lista?|lista[0]|lista.first|lista.get(0)|0|In Python gli indici partono da 0.",
"Come definisci una funzione chiamata saluta?|def saluta():|function saluta()|saluta =>|0|In Python le funzioni si dichiarano con def.",
"Come passi un argomento a una funzione?|def f(x):|function f(){x}|f -> x|0|Si dichiarano parametri tra parentesi.",
"Come ritorni un valore da una funzione?|return x|yield x|output x|0|return restituisce il valore dalla funzione.",
"Come fai una copia superficiale di una lista?|lista.copy()|list(lista)|lista.shallow()|0|copy() crea una copia superficiale della lista.",
"Come concatenare due liste?|lista1 + lista2|lista1.concat(lista2)|lista1.append(lista2)|0|L'operatore + unisce le liste.",
"Come ordini una lista in ordine crescente?|lista.sort()|sorted(lista)|lista.order()|1|sorted() restituisce una lista ordinata senza modificare l'originale.",
"Come ordini una lista senza modificarla?|sorted(lista)|lista.sort()|lista.order()|0|sorted() restituisce una nuova lista ordinata.",
"Come trovi il massimo in una lista?|max(lista)|lista.max()|maximum(lista)|0|max() restituisce il valore massimo.",
"Come trovi il minimo in una lista?|min(lista)|lista.min()|minimum(lista)|0|min() restituisce il valore minimo.",
"Come unisci due dizionari?|dict1.update(dict2)|dict1 + dict2|merge(dict1, dict2)|0|update() unisce i contenuti di dict2 in dict1.",
"Come controlli se una chiave è in un dizionario?|key in dict|dict.has(key)|dict.contains(key)|0|in verifica se la chiave esiste nel dizionario.",
"Come elimini una chiave da un dizionario?|del dict[key]|dict.remove(key)|dict.delete(key)|0|del elimina una chiave dal dizionario.",
"Come si crea un set?|set([1,2,3])|{1,2,3}|[1,2,3]|0|set() crea un insieme unico di elementi.",
"Come aggiungi un elemento a un set?|set.add(4)|set.push(4)|set.append(4)|0|add() aggiunge un elemento al set.",
"Come rimuovi un elemento da un set?|set.remove(4)|set.pop(4)|del set[4]|0|remove() elimina un elemento specifico.",
"Come fai l'intersezione di due set?|set1 & set2|set1.intersect(set2)|set1.merge(set2)|0|L'operatore & restituisce l'intersezione dei set.",
"Come fai l'unione di due set?|set1 | set2|set1.union(set2)|set1 + set2|0|L'operatore | o union() restituisce l'unione dei set.",
"Come fai la differenza tra due set?|set1 - set2|set1.diff(set2)|set1.remove(set2)|0|L'operatore - restituisce gli elementi di set1 non in set2.",
"Come fai una comprensione di lista?|[x*2 for x in lista]|for x in lista: x*2|lista.map(lambda x: x*2)|0|Le comprensioni di lista creano nuove liste in una sola riga.",
"Come fai una comprensione con condizione?|[x for x in lista if x>0]|filter(lambda x: x>0, lista)|for x in lista: if x>0|0|Si può aggiungere if alla comprensione di lista.",
"Come apri un file in lettura?|open('file.txt','r')|file.open('file.txt')|read('file.txt')|0|open() apre file con modalità 'r' per leggere.",
"Come apri un file in scrittura?|open('file.txt','w')|file.write('file.txt')|write('file.txt')|0|Modalità 'w' apre un file per scrivere, sovrascrivendo.",
"Come leggi tutto il contenuto di un file?|file.read()|file.readlines()|read(file)|0|read() restituisce tutto il contenuto del file come stringa.",
"Come leggi riga per riga?|file.readlines()|file.read()|file.line()|0|readlines() restituisce tutte le righe come lista.",
"Come chiudi un file?|file.close()|close(file)|file.end()|0|close() chiude il file e libera risorse.",
"Come usare with per aprire un file?|with open('file.txt','r') as f:|open('file.txt') as f:|file.open('file.txt')|0|with gestisce automaticamente apertura e chiusura del file.",
"Come converti una stringa in intero?|int('123')|str('123')|float('123')|0|int() converte una stringa in numero intero.",
"Come converti una stringa in float?|float('3.14')|int('3.14')|str('3.14')|0|float() converte una stringa in numero decimale.",
"Come converti un numero in stringa?|str(123)|int(123)|float(123)|0|str() converte il numero in stringa.",
"Come importi un modulo?|import math|include math|require('math')|0|import importa un modulo in Python.",
"Come importi solo una funzione da un modulo?|from math import sqrt|import math.sqrt|use math.sqrt|0|from ... import ... importa solo la funzione specifica."
            ],
        L3: ["Come definisci una classe chiamata Persona?|class Persona:|def Persona():|Persona class|0|In Python le classi si definiscono con class.",
"Come erediti da una classe Animal in Python?|class Dog(Animal):|class Dog < Animal:|class Dog inherits Animal|0|La sintassi è class NomeClasse(ClasseBase):",
"Come definisci un metodo speciale per inizializzare un oggetto?|def __init__(self):|def init():|def constructor():|0|Il metodo __init__ è il costruttore in Python.",
"Come accedi a un attributo di istanza di un oggetto?|oggetto.attributo|oggetto->attributo|oggetto[attributo]|0|In Python si usa punto per accedere agli attributi.",
"Come crei un metodo di classe?|@classmethod def metodo(cls):|def metodo():|def metodo(self):|0|@classmethod definisce un metodo legato alla classe.",
"Come crei un metodo statico?|@staticmethod def metodo():|def metodo():|@static def metodo():|0|@staticmethod definisce un metodo non legato a istanza o classe.",
"Come definisci un metodo privato?|def __metodo(self):|def _metodo(self):|def metodo(self):|0|Doppio underscore rende l'attributo o metodo privato.",
"Come usi il polimorfismo con metodi?|def metodo(self):|override del metodo in sottoclasse|entrambi|1|Il polimorfismo permette di ridefinire metodi in sottoclassi.",
"Come sovrascrivi il metodo __str__?|def __str__(self):|def str(self):|def __repr__(self):|0|__str__ definisce la rappresentazione a stringa dell’oggetto.",
"Come usi super() per chiamare il costruttore della classe base?|super().__init__()|super()|Base.__init__()|0|super() richiama metodi della classe base.",
"Come definisci una classe astratta?|from abc import ABC, abstractmethod|class Abstract:|abstract class ABC|0|Si importa ABC e si usano abstractmethod per definire astratte.",
"Come definisci un metodo astratto?|@abstractmethod def metodo(self):|def metodo():|def abstract metodo():|0|@abstractmethod obbliga le sottoclassi a implementarlo.",
"Come implementi un'interfaccia in Python?|class MiaClasse(Interfaccia):|implements Interfaccia|class MiaClasse: Interfaccia|0|In Python si usa ereditarietà per simulare interfacce.",
"Come crei un generatore?|def gen(): yield x|def gen(): return x|def gen(): print(x)|0|yield restituisce valori uno alla volta creando un generatore.",
"Come si usa next() su un generatore?|next(gen)|gen.next()|next.gen()|0|next() restituisce il prossimo valore del generatore.",
"Come si crea una funzione lambda?|lambda x, y: x + y|def f(x, y): return x + y|f = x+y|0|lambda crea funzioni anonime in una sola riga.",
"Come usi map su una lista?|map(lambda x: x*2, lista)|lista.map(lambda x: x*2)|apply(lambda x: x*2, lista)|0|map applica una funzione a tutti gli elementi.",
"Come usi filter su una lista?|filter(lambda x: x>0, lista)|lista.filter(lambda x: x>0)|select(lambda x>0, lista)|0|filter restituisce solo gli elementi che soddisfano la condizione.",
"Come usi reduce su una lista?|from functools import reduce; reduce(f, lista)|lista.reduce(f)|reduce(lista, f)|0|reduce accumula gli elementi secondo la funzione f.",
"Come gestisci eccezioni multiple?|try: ... except (TypeError, ValueError): ...|except TypeError, ValueError:|try/catch TypeError, ValueError|0|Si elencano le eccezioni tra parentesi.",
"Come lanci un’eccezione?|raise ValueError('msg')|throw ValueError('msg')|error('msg')|0|raise genera un’eccezione in Python.",
"Come definisci proprietà getter e setter?|@property / @nome.setter|get()/set()|property()|0|@property permette di creare proprietà gestite.",
"Come introspezioni un oggetto?|dir(obj)|inspect(obj)|obj.info()|0|dir() mostra attributi e metodi di un oggetto.",
"Come usi il modulo inspect per funzioni?|import inspect; inspect.getmembers(obj)|inspect(obj)|obj.inspect()|0|inspect permette di ottenere informazioni dettagliate su oggetti e funzioni.",
"Come definisci metodi speciali per operatori?|def __add__(self, other):|def add(self, other):|def operator_add(self, other):|0|I metodi __nome__ definiscono operatori speciali.",
"Come controlli tipi di oggetti?|isinstance(obj, Classe)|type(obj) == Classe|obj.type == Classe|0|isinstance verifica se un oggetto appartiene a una classe.",
"Come usi decoratori per funzioni?|@decorator def f():|def @decorator f():|decorator(f)|0|Un decoratore modifica il comportamento di una funzione.",
"Come memorizzi valori con functools lru_cache?|@lru_cache()|cache(f)|functools.cache(f)|0|lru_cache memorizza i risultati di funzioni costose.",
"Come lavori con generator expressions?|(x*2 for x in lista)|[x*2 for x in lista]|{x*2 for x in lista}|0|Le generator expressions creano valori su richiesta, senza lista completa.",
"Come lavori con iterators personalizzati?|def __iter__(self): ... def __next__(self): ...|for i in obj|iter(obj)|0|Definendo __iter__ e __next__ si crea un iteratore personalizzato."
            ], L4: ["Come definisci un contesto manager personalizzato?|class MioContesto: def __enter__(self): ... def __exit__(self, exc_type, exc_val, exc_tb): ...|class MioContesto: pass|def context(): ...|0|Definendo __enter__ e __exit__ crei un context manager personalizzato.",
"Come si usa un context manager personalizzato?|with MioContesto() as c: ...|MioContesto().start()|start(MioContesto())|0|with chiama __enter__ all’inizio e __exit__ alla fine.",
"Come usi metaclasses in Python?|class Meta(type): ...|class Meta(): ...|def Meta(): ...|0|Metaclass definisce il comportamento delle classi stesse.",
"Come crei una classe con metaclass?|class MiaClasse(metaclass=Meta): ...|class MiaClasse(Meta): ...|def MiaClasse(): ...|0|Si specifica metaclass=Meta nella definizione della classe.",
"Come usi il decoratore @staticmethod avanzato?|@staticmethod def f(): ...|def f(): ...|@staticmethod f(): ...|0|@staticmethod crea metodi indipendenti dall’istanza.",
"Come usi il decoratore @classmethod avanzato?|@classmethod def f(cls): ...|def f(): ...|@classmethod f(): ...|0|@classmethod crea metodi legati alla classe.",
"Come crei generatori annidati?|def gen(): yield from altro_gen()|yield altro_gen()|for x in altro_gen(): yield x|0|yield from permette di delegare a un altro generatore.",
"Come fai coroutine con async/await?|async def f(): await g()|def f(): yield g()|def f(): async g()|0|async/await definiscono coroutine per operazioni asincrone.",
"Come lanci un task asincrono?|import asyncio; asyncio.create_task(f())|f()|task(f())|0|create_task permette di eseguire coroutine in background.",
"Come gestisci loop asincroni?|asyncio.run(main())|main()|loop.run(main)|0|asyncio.run avvia il loop principale per le coroutine.",
"Come crei descriptor personalizzati?|class Descriptor: def __get__(self,obj,type): ... def __set__(self,obj,val): ...|property|get/set|0|Definendo __get__ e __set__ si controlla accesso e assegnazione di attributi.",
"Come fai weak references?|import weakref; weakref.ref(obj)|ref(obj)|weak(obj)|0|weakref.ref crea riferimento debole a un oggetto.",
"Come fai caching avanzato con functools lru_cache?|@lru_cache(maxsize=128) def f(): ...|cache(f)|@cache def f(): ...|0|lru_cache memorizza i risultati per ridurre calcoli ripetuti.",
"Come usi il modulo threading per thread avanzati?|import threading; t = threading.Thread(target=f); t.start()|thread(f)|thread.start(f)|0|threading.Thread crea e avvia un thread.",
"Come usi threading.Lock per sincronizzazione?|lock = threading.Lock(); lock.acquire(); ...; lock.release()|lock.lock()|lock.sync()|0|Lock previene accesso concorrente a risorse condivise.",
"Come usi threading.Event?|event = threading.Event(); event.wait(); event.set()|event.trigger()|event.start()|0|Event permette di sincronizzare thread tramite segnali.",
"Come lavori con multiprocessing avanzato?|from multiprocessing import Process; p = Process(target=f); p.start()|process(f)|multiprocess(f)|0|multiprocessing permette di creare processi paralleli indipendenti.",
"Come condividi dati tra processi?|from multiprocessing import Queue; q.put(x)|shared_memory|queue.put(x)|0|Queue permette di scambiare dati tra processi in sicurezza.",
"Come usi asyncio.gather per più coroutine?|await asyncio.gather(coro1,coro2)|await coro1 + coro2|gather(coro1,coro2)|0|gather esegue più coroutine contemporaneamente.",
"Come usi asyncio.wait?|done, pending = await asyncio.wait(tasks)|await tasks|wait(tasks)|0|wait permette di attendere più coroutine fino al completamento.",
"Come gestisci exception propagation nelle coroutine?|try: await coro() except Exception as e: ...|coro().catch()|try: coro()|0|Le eccezioni nelle coroutine possono essere catturate con try/except.",
"Come usi contextlib.contextmanager?|from contextlib import contextmanager; @contextmanager def cm(): yield ...|def cm(): ...|contextmanager(cm)|0|@contextmanager semplifica la creazione di context manager.",
"Come crei un singleton avanzato?|def __new__(cls): if not hasattr(cls,'_instance'): cls._instance = super().__new__(cls); return cls._instance|class Singleton(): ...|singleton = Singleton()|0|__new__ permette di controllare l’allocazione dell’istanza.",
"Come fai monkey patching avanzato?|modulo.funzione = nuova_funzione|patch(modulo.funzione)|modulo.override(funzione)|0|Si sovrascrive dinamicamente la funzione o metodo.",
"Come usi metodi speciali per operatori avanzati?|def __mul__(self, other): ...|def multiply(self, other): ...|def __operator_mul__(self, other): ...|0|I metodi __nome__ definiscono comportamenti per operatori come +, *, ecc.",
"Come si usa typing per type hints avanzati?|from typing import List, Dict; def f(x: List[int]) -> Dict[str,int]: ...|def f(x) -> ...|typehint(f)|0|typing fornisce suggerimenti di tipo statici.",
"Come definire classi generiche?|from typing import Generic, TypeVar; T = TypeVar('T'); class MyClass(Generic[T]): ...|class MyClass<T>: ...|GenericClass(T)|0|Generic permette classi parametrizzate da tipi.",
"Come usare __slots__ per ottimizzare memoria?|class C: __slots__ = ['x','y']|class C: pass|__slots__(C)|0|__slots__ limita gli attributi e riduce l’uso di memoria.",
"Come fare introspezione avanzata?|import inspect; inspect.getmembers(obj)|dir(obj)|obj.inspect()|0|inspect permette di esplorare oggetti e classi in dettaglio.",
"Come serializzare oggetti complessi?|import pickle; pickle.dump(obj,f)|json.dump(obj,f)|serialize(obj)|0|pickle permette di salvare oggetti Python complessi su file.",
"Come deserializzare oggetti complessi?|import pickle; obj = pickle.load(f)|json.load(f)|deserialize(f)|0|pickle.load ricrea l’oggetto Python dal file."
                   ]
    },
    JavaScript: {
        L1: ["Esempio JS|Opz 0|Opz 1|Opz 2|0|Spiegazione"],
        L2: [], L3: [], L4: []
    },
    Java: { L1: [], L2: [], L3: [], L4: [] },
    MySQL: { L1: [], L2: [], L3: [], L4: [] },
    HTML: { L1: [], L2: [], L3: [], L4: [] }
};

const challenges5 = {
    Python: { task: "Usa range(1, 4)", logic: "range(1, 4)", output: "1\n2\n3" },
    JavaScript: { task: "Ciclo for", logic: "for", output: "OK" },
    Java: { task: "Main", logic: "main", output: "OK" },
    MySQL: { task: "Select", logic: "SELECT", output: "OK" },
    HTML: { task: "Div", logic: "<div>", output: "OK" }
};
