const domandaRepo = {
    Python: {
        L1: [
            "Come stampi Ciao?|print('Ciao')|echo 'Ciao'|console.log('Ciao')|0|In Python si usa print().",
            "Come assegni il valore 5 alla variabile x?|x == 5|x = 5|5 -> x|1|In Python si usa = per assegnare valori.",
            "Quale tipo di dato è 3.14?|int|str|float|2|3.14 è un numero decimale, quindi float.",
            "Come fai un commento in Python?|# Questo è un commento|// Commento|/* Commento */|0|I commenti iniziano con #.",
            "Come controlli se x è uguale a 10?|x = 10|x == 10|x === 10|1|Per confrontare valori si usa ==.",
            "Come sommi due numeri x e y?|x + y|x add y|x & y|0|In Python l'operatore + somma i numeri.",
            "Come sottrai y da x?|x - y|x sub y|x * y|0|L'operatore - sottrae i valori.",
            "Come moltiplichi x e y?|x * y|x x y|x . y|0|L'operatore * moltiplica i valori.",
            "Come dividi x per y?|x / y|x // y|x % y|0|L'operatore / esegue la divisione.",
            "Come fai il resto della divisione di x per y?|x % y|x / y|x // y|0|L'operatore % calcola il modulo.",
            "Qual è il risultato di 3 ** 2?|6|9|8|1|** è l'operatore di potenza, 3²=9.",
            "Come scrivi una condizione if?|if x > 0:|if(x > 0)|if x > 0 then|0|Python usa if seguito da due punti.",
            "Come scrivi un else?|else:|otherwise|else if|0|Si usa else seguito da :.",
            "Come scrivi un elif?|elif x == 0:|elseif x == 0|else if x == 0|0|elif è elif, non elseif.",
            "Come fai un ciclo for per x in lista?|for x in lista:|for x = lista|for each x in lista|0|Sintassi corretta: for x in lista:",
            "Come fai un ciclo while?|while x < 5:|while(x < 5)|do while x < 5|0|while usa i due punti per iniziare il blocco.",
            "Come interrompi un ciclo?|break|stop|exit|0|break esce dal ciclo immediatamente.",
            "Come salti un’iterazione di un ciclo?|continue|skip|pass|0|continue salta l'iterazione corrente.",
            "Come fai nulla in Python?|pass|null|none|0|pass è un'istruzione nulla.",
            "Qual è il valore booleano vero?|True|TRUE|1|0|In Python True è booleano vero.",
            "Qual è il valore booleano falso?|False|0|Falsey|0|False rappresenta il booleano falso.",
            "Come unisci due stringhe 'Ciao' e 'Mondo'?|'Ciao' + 'Mondo'|'Ciao'.concat('Mondo')|'Ciao'.append('Mondo')|0|L’operatore + concatena le stringhe.",
            "Come ripeti una stringa 3 volte?|'Ciao' * 3|'Ciao'.repeat(3)|'Ciao'.times(3)|0|'Ciao' * 3 = 'CiaoCiaoCiao'.",
            "Come trasformi '123' in numero?|int('123')|str('123')|float('123')|0|int() converte la stringa in intero.",
            "Come trasformi 123 in stringa?|str(123)|int(123)|format(123)|0|str() converte un numero in stringa.",

            "Come stampi più valori?|print(a, b)|echo a b|console.log(a,b)|0|print stampa più argomenti.",
"Come vai a capo?|print()|newline()|\n|0|print() va a capo.",
"Come crei una variabile vuota?|x = None|x = 0|x = ''|0|None indica assenza di valore.",
"Come controlli se due valori sono diversi?|x != y|x <> y|x !== y|0|!= confronta diversità.",
"Come fai AND logico?|x and y|x && y|and(x,y)|0|and è operatore logico.",
"Come fai OR logico?|x or y|x || y|or(x,y)|0|or è operatore logico.",
"Come fai NOT logico?|not x|!x|x not|0|not nega il valore.",
"Come assegni più variabili?|a,b = 1,2|a=1 b=2|set(a,b)|0|Assegnazione multipla.",
"Come ottieni valore assoluto?|abs(x)|absolute(x)|x.abs()|0|abs() valore assoluto.",
"Come elevi 2 a 3?|2 ** 3|pow(2,3,4)|2 ^ 3|0|** è potenza.",
            
            "Come ottieni il tipo di una variabile?|type(x)|typeof x|x.type|0|type() restituisce il tipo.",
            "Come ottieni input da tastiera?|input()|read()|scan()|0|input() legge da input.",
            "Come converti input in intero?|int(input())|input(int)|readInt()|0|Serve int().",
            "Come controlli lunghezza stringa?|len(s)|s.length|count(s)|0|len() restituisce la lunghezza.",
            "Come arrotondi un numero?|round(x)|floor(x)|int(x)|0|round() arrotonda."
        ],

        L2: [
            "Come aggiungi un elemento a una lista chiamata lista?|lista.append(5)|lista.add(5)|lista.push(5)|0|append() aggiunge elementi.",
            "Come ottieni la lunghezza di una lista?|len(lista)|lista.length|lista.size|0|len() restituisce il numero di elementi.",
            "Come gestisci un errore in Python?|try/except|catch|error handling|0|try/except cattura eccezioni.",
            "Come estrai il primo elemento di una lista?|lista[0]|lista.first|lista.get(0)|0|Gli indici partono da 0.",
            "Come definisci una funzione chiamata saluta?|def saluta():|function saluta()|saluta =>|0|def definisce funzioni.",
            "Come ritorni un valore da una funzione?|return x|yield x|output x|0|return restituisce il valore.",
            "Come fai una copia superficiale di una lista?|lista.copy()|list(lista)|lista.shallow()|0|copy() crea una copia.",
            "Come concatenare due liste?|lista1 + lista2|lista1.concat(lista2)|lista1.append(lista2)|0|+ unisce liste.",
            "Come ordini una lista in ordine crescente?|lista.sort()|sorted(lista)|lista.order()|0|sort() ordina la lista.",
            "Come ordini una lista senza modificarla?|sorted(lista)|lista.sort()|lista.order()|0|sorted() restituisce una nuova lista.",

            // +5 nuove L2
            "Come inverti una lista?|lista.reverse()|reverse(lista)|lista.invert()|0|reverse() inverte la lista.",
            "Come rimuovi ultimo elemento?|lista.pop()|lista.remove()|del lista|0|pop() rimuove ultimo.",
            "Come conti occorrenze?|lista.count(x)|count(lista)|x.count()|0|count() conta valori.",
            "Come copi una lista con slicing?|lista[:] |copy(lista)|slice(lista)|0|[:] crea copia.",
            "Come fai enumerate?|enumerate(lista)|list.enumerate()|for index|0|enumerate() fornisce indice.",
            "Come rimuovi un valore specifico?|lista.remove(x)|lista.pop(x)|del x|0|remove elimina valore.",
"Come svuoti una lista?|lista.clear()|lista.empty()|clear(lista)|0|clear svuota lista.",
"Come accedi ultimo elemento?|lista[-1]|lista.last()|lista[end]|0|Indice -1.",
"Come fai slicing?|lista[1:3]|slice(lista)|lista.slice()|0|Slicing con :",
"Come verifichi se elemento esiste?|x in lista|lista.has(x)|exists(x)|0|in controlla presenza.",
"Come crei lista vuota?|[]|list(0)|{}|0|[] crea lista.",
"Come copi lista con list()?|list(lista)|lista.copy()|clone(lista)|0|list() copia.",
"Come ordini al contrario?|lista.sort(reverse=True)|sort(desc)|reverse(sort)|0|reverse=True.",
"Come trasformi stringa in lista?|list(s)|s.split()|array(s)|0|list() separa caratteri.",
"Come unisci stringa da lista?|''.join(lista)|join(lista)|concat(lista)|0|join unisce stringhe."
        ],

        L3: [
            "Come definisci una classe chiamata Persona?|class Persona:|def Persona():|Persona class|0|class definisce classi.",
            "Come erediti da una classe Animal?|class Dog(Animal):|class Dog < Animal:|class Dog inherits Animal|0|Sintassi corretta.",
            "Come definisci il costruttore?|def __init__(self):|def init():|def constructor():|0|__init__ è il costruttore.",
            "Come accedi a un attributo?|oggetto.attributo|oggetto->attributo|oggetto[attributo]|0|Si usa il punto.",
            "Come sovrascrivi __str__?|def __str__(self):|def str(self):|def __repr__(self):|0|__str__ definisce stringa.",
            "Come definisci metodo?|def metodo(self):|function metodo()|method()|0|Metodo usa self.",
"Come crei oggetto?|p = Persona()|new Persona()|Persona.new()|0|Si istanzia così.",
"Come rendi attributo privato?|self._x|private x|__private|0|_ indica uso interno.",
"Come confronti oggetti?|__eq__|equals()|compare()|0|__eq__ definisce ==",
"Come fai repr?|def __repr__(self):|repr()|__str__|0|__repr__ rappresentazione.",
"Come definisci proprietà?|@property|prop()|getter|0|property crea getter.",
"Come definisci setter?|@x.setter|set(x)|setter|0|setter modifica valore.",
"Come fai dataclass?|@dataclass|class data|data()|0|dataclass automatizza.",
"Come gestisci eccezione custom?|class MyError(Exception)|error class|raise error|0|Eccezione custom.",
"Come lanci eccezione?|raise ValueError()|throw error|error()|0|raise lancia errore.",

            // +5 nuove L3
            "Come controlli il tipo?|isinstance(x, Classe)|type(x)==Classe|x is Classe|0|isinstance è corretto.",
            "Come usi super?|super().__init__()|super()|Base.init()|0|super() chiama la base.",
            "Come crei una lambda?|lambda x: x*2|def lambda()|x => x*2|0|lambda crea funzioni anonime.",
            "Come usi map?|map(f, lista)|lista.map(f)|apply(f)|0|map applica funzione.",
            "Come usi filter?|filter(f, lista)|lista.filter()|select(f)|0|filter filtra valori."
        ],

        L4: [
            "Come fai coroutine?|async def f(): await g()|def f(): yield g()|async f()|0|async/await crea coroutine.",
            "Come lanci un task async?|asyncio.create_task(f())|asyncio.run(f)|task(f)|0|create_task avvia task.",
            "Come definisci context manager?|__enter__ / __exit__|with only|context()|0|Serve enter/exit.",
            "Come fai weak reference?|weakref.ref(obj)|ref(obj)|weak(obj)|0|weakref crea ref debole.",
            "Come serializzi oggetti?|pickle.dump(obj,f)|json.dump(obj)|save(obj)|0|pickle serializza oggetti.",
            "Come usi asyncio.run?|asyncio.run(main())|run(async)|start()|0|Avvia event loop.",
"Come definisci generator?|def f(): yield x|gen()|return yield|0|yield crea generatori.",
"Come chiudi generator?|gen.close()|stop(gen)|end()|0|close chiude.",
"Come gestisci timeout async?|asyncio.wait_for()|timeout()|wait()|0|wait_for timeout.",
"Come fai thread?|threading.Thread()|async thread|run thread|0|Threading base.",
"Come fai lock?|threading.Lock()|mutex()|lock()|0|Lock sincronizza.",
"Come usi contextlib?|@contextmanager|with only|ctx()|0|Context manager rapido.",
"Come usi functools?|import functools|use func|fun()|0|Utility funzionali.",
"Come usi partial?|functools.partial|partial()|bind()|0|Partial applica argomenti.",
"Come tipi ritorno?|def f() -> int|return int|int f()|0|Type hint ritorno.",

            // +5 nuove L4
            "Come usi yield from?|yield from gen()|yield gen()|for yield|0|yield from delega.",
            "Come crei iteratori?|__iter__ e __next__|for loop|range|0|Definisce iteratore.",
            "Come usi lru_cache?|@lru_cache()|@cache|cache(f)|0|Memorizza risultati.",
            "Come definisci __slots__?|__slots__=['x']|slots()|@slots|0|Riduce memoria.",
            "Come usi typing?|from typing import List|type(list)|hint()|0|typing fornisce hint."
        ]
    },
    JavaScript: {
        L1: [
            "Come stampi Ciao?|console.log('Ciao')|print('Ciao')|echo 'Ciao'|0|console.log stampa in console.",
            "Come dichiari una variabile?|let x = 5|var: x = 5|int x = 5|0|let dichiara variabili.",
            "Che tipo è 'ciao'?|string|String|text|0|'ciao' è una stringa.",
            "Come fai un commento?|// commento|# commento|<!-- -->|0|// è il commento JS.",
            "Come confronti due valori uguali?|==|=|=>|0|== confronta valori.",

            "Come dichiari costante?|const x = 5|let x|var x|0|const è costante.",
"Che valore ha undefined?|undefined|null|0|0|undefined è non assegnato.",
"Che valore ha null?|null|undefined|false|0|null è valore vuoto.",
"Come converti stringa a numero?|Number(s)|parse(s)|int(s)|0|Number converte.",
"Come converti numero a stringa?|String(x)|x.toInt()|text(x)|0|String converte.",
"Come controlli tipo?|typeof x|type(x)|x.type|0|typeof ritorna tipo.",
"Come fai boolean true?|true|True|1|0|true boolean.",
"Come fai boolean false?|false|False|0|0|false boolean.",
"Come concateni stringhe?|a + b|a.concat(b)|join(a,b)|0|+ concatena.",
"Come accedi carattere?|s[0]|s.char(0)|s.get(0)|0|Indice stringa.",
"Come lunghezza stringa?|s.length|len(s)|size(s)|0|length stringa.",
"Come maiuscolo?|s.toUpperCase()|upper(s)|s.big()|0|toUpperCase.",
"Come minuscolo?|s.toLowerCase()|lower(s)|s.small()|0|toLowerCase.",
"Come confronto diverso?|!=|<>|!==|0|!= diverso.",
"Come confronto stretto diverso?|!==|!=|<>|0|!== tipo+valore.",
"Come incrementi?|x++|++x+|x+1|0|++ incrementa.",
"Come decrementi?|x--|--x-|x-1|0|-- decrementa.",
"Come fai if?|if(x>0){}|if x>0|if(x)|0|if condizione.",
"Come fai else?|else{}|otherwise{}|else if|0|else ramo.",
"Come fai ternario?|x? a:b|if else|tern(x)|0|Operatore ternario.",
"Come commento multi?|/* */|//|<!-- -->|0|Commento multi.",
"Come fai NaN?|NaN|0|undefined|0|NaN non numero.",
"Come controlli NaN?|isNaN(x)|x==NaN|typeof NaN|0|isNaN controlla.",
"Come arrotondi?|Math.round(x)|round(x)|int(x)|0|Math.round.",
"Come floor?|Math.floor(x)|floor(x)|round(x)|0|Math.floor.",
"Come ceil?|Math.ceil(x)|ceil(x)|round(x)|0|Math.ceil.",
"Come random?|Math.random()|random()|rand|0|Numero casuale.",
"Come potenza?|Math.pow(a,b)|a**b|pow(a,b,c)|1|Entrambi validi.",
"Come resto?|a % b|mod(a,b)|a/b|0|Modulo.",
"Come confronto maggiore?|a > b|a gt b|compare(a,b)|0|> maggiore.",
            // +5 nuove L1
            "Come confronti tipo e valore?|===|==|=|0|=== è confronto stretto.",
            "Come sommi 2 numeri?|a + b|a plus b|add(a,b)|0|+ somma.",
            "Come sottrai?|a - b|a minus b|sub(a,b)|0|- sottrae.",
            "Come moltiplichi?|a * b|a x b|mul(a,b)|0|* moltiplica.",
            "Come dividi?|a / b|a : b|div(a,b)|0|/ divide."
        ],

        L2: [
            "Come crei una funzione?|function f(){}|def f()|fun f()|0|function definisce funzioni.",
            "Come ritorni un valore?|return x|yield x|output x|0|return restituisce valore.",
            "Come crei un array?|[1,2,3]|array(1,2,3)|{1,2,3}|0|[] crea array.",
            "Come accedi al primo elemento?|arr[0]|arr.first|arr.get(0)|0|Indice 0.",
            "Come aggiungi elemento a array?|arr.push(5)|arr.add(5)|push(arr,5)|0|push aggiunge.",
            "Come rimuovi primo?|arr.shift()|arr.pop()|remove(0)|0|shift rimuove primo.",
"Come aggiungi primo?|arr.unshift(x)|arr.push(x)|addFirst|0|unshift aggiunge.",
"Come slice array?|arr.slice(1,3)|arr.cut()|slice(arr)|0|slice copia.",
"Come splice array?|arr.splice()|arr.slice()|remove()|0|splice modifica.",
"Come trova elemento?|arr.find(f)|arr.search()|find(arr)|0|find restituisce.",
"Come trova indice?|arr.findIndex(f)|arr.index()|where()|0|Indice trovato.",
"Come filtri?|arr.filter(f)|arr.find()|where()|0|filter filtra.",
"Come riduci?|arr.reduce(f)|sum(arr)|fold()|0|reduce accumula.",
"Come controlli tutti?|arr.every(f)|all(arr)|each()|0|every verifica.",
"Come controlli uno?|arr.some(f)|any(arr)|one()|0|some verifica.",
"Come ordini?|arr.sort()|order(arr)|sort(arr)|0|sort ordina.",
"Come inverti?|arr.reverse()|invert(arr)|flip()|0|reverse inverte.",
"Come converti stringa in array?|s.split(',')|toArray(s)|array(s)|0|split divide.",
"Come verifica include?|arr.includes(x)|has(x)|contains(x)|0|includes verifica.",
"Come ciclo for?|for(let i=0;i<n;i++)|loop|foreach|0|for classico.",
"Come ciclo for..of?|for(const x of arr)|foreach|loop of|0|for..of valori.",
"Come oggetto?|{}|new Object[]|object()|0|{} crea oggetto.",
"Come accedi proprietà?|obj.x|obj->x|obj(x)|0|Punto.",
"Come accedi dinamico?|obj['x']|obj.x()|get(obj)|0|[] dinamico.",
"Come aggiungi proprietà?|obj.x=1|add(obj)|push(obj)|0|Assegnazione.",
"Come elimina proprietà?|delete obj.x|remove(obj.x)|del x|0|delete rimuove.",
"Come ottieni chiavi?|Object.keys(o)|o.keys()|keys(o)|0|keys restituisce.",
"Come ottieni valori?|Object.values(o)|o.values()|vals(o)|0|values.",
"Come entries?|Object.entries(o)|pairs(o)|map(o)|0|entries coppie.",
"Come clona array?|[...arr]|clone(arr)|copy(arr)|0|Spread.",
"Come merge array?|[...a,...b]|a+b|merge(a,b)|0|Spread merge.",
"Come default param?|f(x=1)|f(x)||0|Default param.",
"Come rest param?|...args|rest(args)|var args|0|Rest raccoglie.",
"Come arrow?|x=>x*2|function(x)|lambda|0|Arrow function.",
"Come callback?|f(()=>{})|call(f)|cb()|0|Callback funzione.",

            // +5 nuove L2
            "Come rimuovi ultimo elemento?|arr.pop()|arr.remove()|pop(arr)|0|pop rimuove ultimo.",
            "Come ottieni lunghezza?|arr.length|len(arr)|size(arr)|0|length è proprietà.",
            "Come unisci array?|a.concat(b)|a + b|merge(a,b)|0|concat unisce.",
            "Come iteri array?|forEach()|loop()|iterate()|0|forEach itera.",
            "Come mappi array?|map()|foreach()|loop()|0|map trasforma."
        ],

        L3: [
            "Come definisci una classe?|class A {}|function A(){}|new Class()|0|class definisce classi.",
            "Come crei un oggetto?|new A()|A()|object A|0|new istanzia.",
            "Come erediti?|class B extends A{}|class B:A|inherit A|0|extends eredita.",
            "Come definisci costruttore?|constructor(){}|init(){}|new(){}|0|constructor è speciale.",
            "Come accedi a proprietà?|obj.prop|obj->prop|obj[prop()]|0|Si usa il punto.",
            "Come metodo?|f(){}|function|method()|0|Metodo classe.",
"Come campo?|this.x|self.x|me.x|0|Campo oggetto.",
"Come getter?|get x()|getter x|x()|0|get definisce.",
"Come setter?|set x(v)|setter x|x(v)|0|set definisce.",
"Come privato?|#x|_x|private x|0|# privato.",
"Come eredita?|extends|implements|inherits|0|extends eredita.",
"Come super?|super()|parent()|base()|0|super chiama base.",
"Come override?|stesso nome|@override|replace|0|Override automatico.",
"Come modulo?|export|module|package|0|Modulo JS.",
"Come named export?|export {x}|export x|public x|0|Named export.",
"Come import named?|import {x}|require x|load x|0|Import named.",
"Come import all?|import * as m|import all|load *|0|Import tutto.",
"Come default export?|export default f|export f|main export|0|Default.",
"Come default import?|import f from|require f|load f|0|Import default.",
"Come instanceof?|x instanceof A|type(x)|is A|0|instanceof verifica.",
"Come prototype?|A.prototype.x|A.x|proto(x)|0|prototype condiviso.",
"Come aggiungi prototype?|A.prototype.f=|add proto|extend|0|Estende classe.",
"Come binding this?|this.bind(f)|bind(this)|lock this|0|bind fissa this.",
"Come call?|f.call(o)|call f|invoke|0|call set this.",
"Come apply?|f.apply(o,args)|apply f|call array|0|apply array args.",
"Come JSON string?|JSON.stringify(o)|toJSON(o)|string(o)|0|stringify.",
"Come JSON parse?|JSON.parse(s)|parseJSON|toObj|0|parse JSON.",
"Come data?|new Date()|Date()|now()|0|Date oggetto.",
"Come timestamp?|Date.now()|time()|timestamp()|0|now ms.",
"Come regex?|/a+/|regex(a)|new Regex|0|Regex literal.",
"Come test regex?|r.test(s)|match|check|0|test boolean.",
"Come match?|s.match(r)|find|search|0|match risultati.",
"Come replace?|s.replace(a,b)|swap|change|0|replace stringa.",
"Come trim?|s.trim()|cut|strip|0|trim spazi.",
"Come pad?|s.padStart(2)|pad(s)|fill|0|padStart.",
"Come locale compare?|s.localeCompare(t)|compare|sort|0|Confronto locale.",

            // +5 nuove L3
            "Come fai metodo statico?|static f(){}|function static f|class static|0|static crea metodo.",
            "Come esporti modulo?|export default x|module x|public x|0|export esporta.",
            "Come importi modulo?|import x from 'x'|include x|require x|0|import carica.",
            "Come usi this?|this.x|self.x|me.x|0|this è contesto.",
            "Come controlli array?|Array.isArray(x)|typeof x|x is array|0|isArray verifica."
        ],

        L4: [
            "Come definisci funzione async?|async function f(){}|function async f|async f()|0|async abilita await.",
            "Come attendi promessa?|await p|wait p|then p|0|await aspetta.",
            "Come crei Promise?|new Promise()|Promise()|promise{}|0|Promise costruttore.",
            "Come gestisci errori?|try/catch|if error|onerror|0|try/catch gestisce.",
            "Come fai fetch?|fetch(url)|get(url)|request(url)|0|fetch fa richieste.",
            "Cos'è event loop?|Gestione async|Thread|Promise|0|Event loop JS.",
"Cos'è microtask?|Promise queue|Macro|Thread|0|Microtask priorità.",
"then?|p.then(f)|await|catch|0|then gestisce risultato.",
"catch?|p.catch(e)|error|throw|0|catch errori.",
"finally?|p.finally()|end()|close()|0|finally sempre.",
"Promise.all?|Promise.all(arr)|wait all|join|0|Attende tutte.",
"Promise.race?|Promise.race(arr)|first|any|0|Prima risolta.",
"Promise.any?|Promise.any(arr)|some|one|0|Prima ok.",
"async arrow?|const f=async()=>{}|async f|await()=>|0|Arrow async.",
"await errore?|try/catch|if|then|0|Gestione errori.",
"setTimeout?|setTimeout(f,ms)|delay|sleep|0|Ritardo.",
"setInterval?|setInterval(f,ms)|loop|repeat|0|Ripete.",
"clearTimeout?|clearTimeout(id)|stop|end|0|Cancella timeout.",
"clearInterval?|clearInterval(id)|stop|end|0|Cancella interval.",
"AbortController?|new AbortController()|abort()|stop|0|Cancella fetch.",
"fetch headers?|headers:{}|meta|config|0|Header fetch.",
"fetch method?|method:'POST'|type|send|0|Metodo HTTP.",
"fetch body?|body: JSON|string|data|0|Body richiesta.",
"Web Storage?|localStorage|cookie|session|0|Storage browser.",
"localStorage set?|setItem(k,v)|save|put|0|Salva valore.",
"localStorage get?|getItem(k)|load|get|0|Legge valore.",
"sessionStorage?|sessionStorage|local|cache|0|Storage sessione.",
"Debounce?|ritardo funzione|loop|throttle|0|Debounce eventi.",
"Throttle?|limita chiamate|delay|debounce|0|Throttle limita.",
"Worker?|new Worker()|thread|process|0|Web Worker.",
"Module defer?|type='module'|async|load|0|Module script.",
"Optional await?|top-level await|await ovunque|global await|0|Await modulo.",
"Dynamic import?|import()|require()|load|0|Import dinamico.",
"Tree shaking?|Elimina unused|minify|bundle|0|Tree shaking.",
"Bundler?|Vite/Webpack|Browser|Node|0|Bundler tool.",

            // +5 nuove L4
            "Come cloni oggetto?|{...obj}|clone(obj)|copy(obj)|0|spread clona.",
            "Come destrutturi?|const {a}=obj|get a|obj[a]|0|destructuring estrae.",
            "Come usa optional chaining?|obj?.a|obj.a?|if obj|0|?. evita errori.",
            "Come usa nullish?|a ?? b|a || b|null(a,b)|0|?? gestisce null.",
            "Come congeli oggetto?|Object.freeze(o)|freeze(o)|lock(o)|0|freeze blocca."
        ]
    },
    Java: {
        L1: [
            "Come stampi Ciao?|System.out.println(\"Ciao\");|print(\"Ciao\")|echo Ciao|0|println stampa testo.",
            "Come dichiari una variabile int?|int x = 5;|x = 5;|var x = 5;|0|int dichiara interi.",
            "Che tipo è 3.14?|double|int|float|0|3.14 è double.",
            "Come fai un commento?|// commento|# commento|<!-- -->|0|// commento singola linea.",
            "Come confronti due numeri?|==|=|equals|0|== confronta primitivi.",
            "Che tipo è true?|boolean|Boolean|bool|0|boolean primitivo.",
"Come dichiari boolean?|boolean x=true;|bool x|Boolean x|0|boolean Java.",
"Come fai if?|if(x>0){}|if x>0|when|0|if condizione.",
"Come fai else?|else{}|otherwise|elif|0|else ramo.",
"Come fai while?|while(x<5){}|loop|for while|0|while ciclo.",
"Come fai do-while?|do{}while(x);|while do|loop|0|do-while esegue prima.",
"Come incrementi?|x++|++x+|x+1|0|Incremento.",
"Come decrementi?|x--|--x-|x-1|0|Decremento.",
"Come confronto >?|a > b|gt|compare|0|Maggiore.",
"Come confronto <?|a < b|lt|compare|0|Minore.",
"Come confronto diverso?|a != b|<>|not equal|0|Diverso.",
"Come AND?|a && b|and|&|0|AND logico.",
"Come OR?|a || b|or||0|OR logico.",
"Come NOT?|!a|not a|~a|0|NOT logico.",
"Come commento multi?|/* */|//|<!-- -->|0|Commento multi.",
"Come cast int?| (int)x |int(x)|cast x|0|Casting.",
"Come parse double?|Double.parseDouble(s)|double(s)|parse(s)|0|Parse double.",
"Come concat stringhe?|a + b|concat(a,b)|join|0|+ concatena.",
"Come lunghezza stringa?|s.length()|len(s)|size()|0|length().",
"Come charAt?|s.charAt(0)|s[0]|getChar|0|charAt.",
"Come substring?|s.substring(1)|slice|cut|0|substring.",
"Come equalsIgnoreCase?|s.equalsIgnoreCase(t)|equals|compare|0|Ignore case.",
"Come toUpperCase?|s.toUpperCase()|upper|big|0|Maiuscolo.",
"Come toLowerCase?|s.toLowerCase()|lower|small|0|Minuscolo.",
"Come array vuoto?|new int[5]|[]|int()|0|Array size fissa.",
"Come boolean array?|boolean[] a|bool[]|array bool|0|Array boolean.",
"Come stampa senza newline?|System.out.print()|println|echo|0|print.",
"Come escape stringa?|\"Ciao\"|\'Ciao\'|escape()|0|Escape \".",
"Come main?|public static void main|start()|run()|0|Entry point.",

            // +5 nuove L1
            "Come sommi due int?|a + b|a plus b|add(a,b)|0|+ somma.",
            "Come sottrai?|a - b|a minus b|sub(a,b)|0|- sottrae.",
            "Come moltiplichi?|a * b|a x b|mul(a,b)|0|* moltiplica.",
            "Come dividi?|a / b|a : b|div(a,b)|0|/ divide.",
            "Come fai modulo?|a % b|a mod b|mod(a,b)|0|% resto."
        ],

        L2: [
            "Come crei un array?|int[] a = {1,2,3};|array a = (1,2,3)|int a = []|0|Array con {}.",
            "Come accedi primo elemento?|a[0]|a.first()|a.get(0)|0|Indice parte da 0.",
            "Come ottieni lunghezza array?|a.length|len(a)|a.size()|0|length è proprietà.",
            "Come fai ciclo for?|for(int i=0;i<5;i++)|for i in range(5)|foreach i|0|Sintassi for.",
            "Come definisci metodo?|static void f(){}|def f()|function f()|0|Metodo Java.",
            "Come ArrayList?|new ArrayList<>()|ArrayList()|list()|0|ArrayList.",
"Come import ArrayList?|import java.util.ArrayList|java.list|list|0|Import.",
"Come size list?|list.size()|length|count|0|size().",
"Come get elemento?|list.get(0)|list[0]|first()|0|get().",
"Come set elemento?|list.set(0,x)|list[0]=x|replace|0|set().",
"Come remove index?|list.remove(0)|delete|pop|0|remove index.",
"Come remove valore?|list.remove(x)|delete x|pop x|0|remove object.",
"Come contains?|list.contains(x)|has|in|0|contains.",
"Come clear?|list.clear()|empty|reset|0|clear.",
"Come isEmpty?|list.isEmpty()|empty?|size==0|0|isEmpty.",
"Come foreach?|for(Type x:list)|loop|each|0|Enhanced for.",
"Come break?|break|stop|exit|0|break.",
"Come continue?|continue|skip|next|0|continue.",
"Come switch?|switch(x)|if chain|case x|0|switch.",
"Come case?|case 1:|if|when|0|case.",
"Come default?|default:|else|otherwise|0|default.",
"Come enum?|enum Giorni{}|Enum|const|0|enum.",
"Come try?|try{}|attempt|error|0|try.",
"Come catch?|catch(Exception e)|handle|except|0|catch.",
"Come finally?|finally{}|end|close|0|finally.",
"Come input?|Scanner sc|input()|read()|0|Scanner.",
"Come import Scanner?|import java.util.Scanner|java.io|scanner|0|Import.",
"Come nextInt?|sc.nextInt()|readInt|int()|0|Legge int.",
"Come nextLine?|sc.nextLine()|readLine|getLine|0|Legge linea.",
"Come Math max?|Math.max(a,b)|max(a,b)|bigger|0|max.",
"Come Math min?|Math.min(a,b)|min(a,b)|smaller|0|min.",
"Come Math abs?|Math.abs(x)|abs(x)|absolute|0|abs.",
"Come Random?|new Random()|Math.random|rand|0|Random class.",
"Come import Random?|import java.util.Random|math|random|0|Import Random.",

            // +5 nuove L2
            "Come fai foreach?|for(int x : a)|foreach x in a|for a|0|Enhanced for.",
            "Come ritorni valore?|return x;|yield x|output x|0|return restituisce.",
            "Come converti String a int?|Integer.parseInt(s)|int(s)|parse(s)|0|parseInt converte.",
            "Come confronti String?|s.equals(t)|s==t|compare(s,t)|0|equals confronta.",
            "Come aggiungi a ArrayList?|list.add(x)|list.push(x)|add(list,x)|0|add inserisce."
        ],

        L3: [
            "Come definisci una classe?|class A {}|def A()|A = class|0|class definisce.",
            "Come crei oggetto?|new A()|A()|create A|0|new istanzia.",
            "Come erediti?|class B extends A|class B:A|inherit A|0|extends eredita.",
            "Come definisci costruttore?|A(){}|constructor(){}|init(){}|0|Costruttore = nome classe.",
            "Come accedi a campo?|obj.x|obj->x|obj[x]|0|Si usa il punto.",
            "Come ArrayList?|new ArrayList<>()|ArrayList()|list()|0|ArrayList.",
"Come import ArrayList?|import java.util.ArrayList|java.list|list|0|Import.",
"Come size list?|list.size()|length|count|0|size().",
"Come get elemento?|list.get(0)|list[0]|first()|0|get().",
"Come set elemento?|list.set(0,x)|list[0]=x|replace|0|set().",
"Come remove index?|list.remove(0)|delete|pop|0|remove index.",
"Come remove valore?|list.remove(x)|delete x|pop x|0|remove object.",
"Come contains?|list.contains(x)|has|in|0|contains.",
"Come clear?|list.clear()|empty|reset|0|clear.",
"Come isEmpty?|list.isEmpty()|empty?|size==0|0|isEmpty.",
"Come foreach?|for(Type x:list)|loop|each|0|Enhanced for.",
"Come break?|break|stop|exit|0|break.",
"Come continue?|continue|skip|next|0|continue.",
"Come switch?|switch(x)|if chain|case x|0|switch.",
"Come case?|case 1:|if|when|0|case.",
"Come default?|default:|else|otherwise|0|default.",
"Come enum?|enum Giorni{}|Enum|const|0|enum.",
"Come try?|try{}|attempt|error|0|try.",
"Come catch?|catch(Exception e)|handle|except|0|catch.",
"Come finally?|finally{}|end|close|0|finally.",
"Come input?|Scanner sc|input()|read()|0|Scanner.",
"Come import Scanner?|import java.util.Scanner|java.io|scanner|0|Import.",
"Come nextInt?|sc.nextInt()|readInt|int()|0|Legge int.",
"Come nextLine?|sc.nextLine()|readLine|getLine|0|Legge linea.",
"Come Math max?|Math.max(a,b)|max(a,b)|bigger|0|max.",
"Come Math min?|Math.min(a,b)|min(a,b)|smaller|0|min.",
"Come Math abs?|Math.abs(x)|abs(x)|absolute|0|abs.",
"Come Random?|new Random()|Math.random|rand|0|Random class.",
"Come import Random?|import java.util.Random|math|random|0|Import Random.",

            // +5 nuove L3
            "Come fai override?|@Override|override|@extend|0|Annotazione override.",
            "Come definisci metodo statico?|static void f()|void static f()|function f()|0|static su metodo.",
            "Come rendi campo privato?|private int x;|int x private|hide x|0|private nasconde.",
            "Come usi super?|super()|base()|parent()|0|super chiama padre.",
            "Come implementi interfaccia?|implements I|extends I|uses I|0|implements interfaccia."
        ],

        L4: [
            "Come gestisci eccezioni?|try/catch|if error|onerror|0|try/catch.",
            "Come lanci eccezione?|throw new Exception()|raise Exception()|error()|0|throw lancia.",
            "Come usi generics?|List<String>|List(str)|Array<String>|0|Generics tipizzano.",
            "Come crei thread?|new Thread()|thread()|Thread.create()|0|Thread Java.",
            "Come sincronizzi metodo?|synchronized|lock|mutex|0|synchronized protegge.",
            "Checked exception?|Compile time|Runtime|Logic|0|Checked.",
"Unchecked exception?|RuntimeException|Compile|Error|0|Unchecked.",
"Throws?|throws Exception|throw|raise|0|Dichiara.",
"Custom exception?|extends Exception|new Error|throw|0|Eccezione custom.",
"Try-with-resources?|try(...)|auto close|finally|0|Auto close.",
"AutoCloseable?|implements AutoCloseable|close()|finalize|0|Resource.",
"Thread start?|t.start()|t.run()|run()|0|start.",
"Runnable?|implements Runnable|Thread|Process|0|Runnable.",
"Lambda Runnable?|()->{}|function|method|0|Lambda.",
"ExecutorService?|Executors.new|Thread|Pool|0|Thread pool.",
"Shutdown executor?|shutdown()|close()|stop()|0|Shutdown.",
"Callable?|Callable<T>|Runnable|Task|0|Ritorna valore.",
"Future?|Future<T>|Result|Promise|0|Risultato async.",
"Wait/notify?|wait() notify()|sleep|lock|0|Monitor.",
"Synchronized block?|synchronized(obj)|lock|mutex|0|Sync block.",
"Volatile?|volatile int x|atomic|sync|0|Visibilità.",
"Atomic int?|AtomicInteger|volatile|int|0|Atomico.",
"Stream source?|list.stream()|stream(list)|flow|0|Source.",
"Intermediate?|map filter|forEach|collect|0|Intermedio.",
"Terminal?|forEach collect|map|filter|0|Terminale.",
"Parallel stream?|parallelStream()|thread|async|0|Parallel.",
"Optional?|Optional<T>|Nullable|Maybe|0|Optional.",
"Optional get?|get()|value()|unwrap|0|get valore.",
"Optional orElse?|orElse(x)|else|default|0|Default.",
"Path?|java.nio.Path|File|URL|0|Path moderno.",
"Files read?|Files.readAllLines|read|load|0|Files.",
"Serialization?|implements Serializable|save|pickle|0|Serializza.",
"Deserialization?|ObjectInputStream|load|read|0|Deserializza.",
"JVM?|Java Virtual Machine|Compiler|Runtime|0|JVM.",
"Garbage Collector?|GC|delete|free|0|Memoria automatica.",

            // +5 nuove L4
            "Come usi lambda?|x -> x+1|lambda x|function(x)|0|Lambda Java.",
            "Come usi stream?|list.stream()|list.flow()|stream(list)|0|Stream API.",
            "Come filtri stream?|filter(x->x>0)|where(x)|select(x)|0|filter filtra.",
            "Come mappi stream?|map(x->x*2)|transform(x)|each(x)|0|map trasforma.",
            "Come raccogli?|collect()|gather()|toList()|0|collect raccoglie."
        ]
    },
    MySQL: {
        L1: [
            "Come selezioni tutti i dati da una tabella?|SELECT * FROM tabella;|GET * FROM tabella;|FETCH tabella;|0|SELECT * legge tutti i dati.",
            "Come inserisci un record?|INSERT INTO tabella VALUES();|ADD RECORD tabella;|PUT tabella;|0|INSERT aggiunge dati.",
            "Come aggiorni dati?|UPDATE tabella SET col=1;|MODIFY tabella;|CHANGE tabella;|0|UPDATE modifica dati.",
            "Come cancelli dati?|DELETE FROM tabella;|REMOVE tabella;|DROP tabella;|0|DELETE cancella righe.",
            "Come filtri risultati?|WHERE|FILTER|IF|0|WHERE filtra righe.",
            "Come selezioni colonna?|SELECT a FROM t|GET a|FETCH a|0|Seleziona colonna.",
"Come alias tabella?|FROM tabella t|AS t|RENAME|0|Alias tabella.",
"Come maggiore?|WHERE a > 5|GT|COMPARE|0|Filtro >.",
"Come minore?|WHERE a < 5|LT|COMPARE|0|Filtro <.",
"Come diverso?|WHERE a <> 5|!=|NOT|0|Diverso.",
"Come AND?|WHERE a=1 AND b=2|&|+|0|AND.",
"Come OR?|WHERE a=1 OR b=2|||0|OR.",
"Come BETWEEN?|BETWEEN 1 AND 5|RANGE|FROM|0|Intervallo.",
"Come IN?|IN (1,2)|EQUALS|ANY|0|IN lista.",
"Come LIKE?|LIKE '%a%'|MATCH|FIND|0|Pattern.",
"Come inizia?|LIKE 'a%'|START|BEGIN|0|Prefisso.",
"Come finisce?|LIKE '%a'|END|STOP|0|Suffisso.",
"Come is null?|IS NULL|=NULL|NULL()|0|Valore null.",
"Come not null?|IS NOT NULL|!=NULL|HAS|0|Non null.",
"Come somma?|SUM(col)|ADD|TOTAL|0|Somma.",
"Come media?|AVG(col)|MEAN|MID|0|Media.",
"Come minimo?|MIN(col)|LOW|SMALL|0|Min.",
"Come massimo?|MAX(col)|HIGH|BIG|0|Max.",
"Come arrotonda?|ROUND(x)|INT|FLOOR|0|Round.",
"Come floor?|FLOOR(x)|ROUND|INT|0|Floor.",
"Come ceil?|CEILING(x)|ROUND|INT|0|Ceil.",
"Come concat?|CONCAT(a,b)|a+b|JOIN|0|Concat.",
"Come lunghezza?|LENGTH(s)|LEN|SIZE|0|Length.",
"Come substring?|SUBSTRING(s,1,2)|CUT|SLICE|0|Substring.",
"Come upper?|UPPER(s)|CAPS|BIG|0|Maiuscolo.",
"Come lower?|LOWER(s)|SMALL|MIN|0|Minuscolo.",
"Come data corrente?|NOW()|DATE()|TIME()|0|Data ora.",
"Come solo data?|CURDATE()|NOW()|DATE|0|Solo data.",
"Come solo ora?|CURTIME()|TIME()|NOW|0|Solo ora.",
"Come formato data?|DATE_FORMAT()|FORMAT|CAST|0|Formatta.",

            
            // +5 nuove L1
            "Come ordini risultati?|ORDER BY col|SORT col|GROUP col|0|ORDER BY ordina.",
            "Come limiti risultati?|LIMIT 5|TOP 5|MAX 5|0|LIMIT limita.",
            "Come eviti duplicati?|DISTINCT|UNIQUE|NODUP|0|DISTINCT elimina duplicati.",
            "Come conti righe?|COUNT(*)|SUM(*)|TOTAL|0|COUNT conta.",
            "Come rinomini colonna?|AS|RENAME|ALIAS|0|AS crea alias."
        ],

        L2: [
            "Come unisci tabelle?|JOIN|MERGE|UNION|0|JOIN unisce tabelle.",
            "Come fai LEFT JOIN?|LEFT JOIN|LEFT MERGE|OUTER LEFT|0|LEFT JOIN include null.",
            "Come raggruppi?|GROUP BY|ORDER BY|COLLECT|0|GROUP BY raggruppa.",
            "Come filtri gruppi?|HAVING|WHERE|FILTER|0|HAVING filtra gruppi.",
            "Come crei indice?|CREATE INDEX|ADD INDEX|MAKE INDEX|0|INDEX velocizza.",
            "INNER JOIN?|JOIN|INNER|MERGE|0|Default join.",
"ON?|ON a.id=b.id|WHERE|LINK|0|Condizione join.",
"Alias colonna?|SELECT a AS x|RENAME|LABEL|0|Alias colonna.",
"COUNT colonna?|COUNT(col)|SUM|TOTAL|0|Conta non null.",
"GROUP + COUNT?|GROUP BY|ORDER BY|JOIN|0|Raggruppa.",
"HAVING vs WHERE?|HAVING gruppi|WHERE righe|same|0|Differenza.",
"Subquery?|SELECT (SELECT)|JOIN|MERGE|0|Query annidata.",
"IN subquery?|IN (SELECT)|JOIN|EXISTS|0|Subquery IN.",
"EXISTS?|EXISTS(SELECT)|IN|HAS|0|Verifica esistenza.",
"NOT EXISTS?|NOT EXISTS|!=|NO|0|Negazione.",
"LIMIT offset?|LIMIT 5 OFFSET 10|SKIP|PAGE|0|Paginazione.",
"ORDER multiplo?|ORDER BY a,b|SORT|GROUP|0|Multi colonna.",
"Indice multiplo?|CREATE INDEX(a,b)|INDEX|KEY|0|Indice composto.",
"Unique index?|CREATE UNIQUE INDEX|DISTINCT|ONLY|0|Indice unico.",
"Drop table if?|DROP TABLE IF EXISTS|DELETE|REMOVE|0|Sicuro.",
"Create if?|CREATE TABLE IF NOT EXISTS|MAKE|NEW|0|Sicuro.",
"Alter add col?|ALTER TABLE ADD col|NEW COL|INSERT|0|Aggiunge.",
"Alter drop col?|ALTER TABLE DROP col|REMOVE|DELETE|0|Rimuove.",
"Rename col?|CHANGE col|RENAME|ALTER NAME|0|Rinomina.",
"Modify tipo?|MODIFY col|CHANGE|CAST|0|Cambia tipo.",
"Engine?|ENGINE=InnoDB|TYPE|MODE|0|Motore.",
"Charset?|CHARSET=utf8|ENCODE|LANG|0|Charset.",
"Collation?|COLLATE|SORT|COMPARE|0|Confronto.",
"Explain?|EXPLAIN SELECT|PLAN|DEBUG|0|Query plan.",
"Index scan?|Using index|Full scan|Join|0|Ottimizzazione.",
"Full scan?|No index|Index|Fast|0|Lento.",
"Temporary?|Using temporary|CACHE|MEM|0|Temp table.",
"Filesort?|Using filesort|ORDER|SORT|0|Sort su disco.",
"Analyze?|ANALYZE TABLE|CHECK|DEBUG|0|Statistiche.",

            // +5 nuove L2
            "Come unisci senza duplicati?|UNION|JOIN|MERGE|0|UNION elimina duplicati.",
            "Come unisci con duplicati?|UNION ALL|UNION|JOIN|0|UNION ALL mantiene.",
            "Come vedi struttura tabella?|DESCRIBE tabella|SHOW tabella|INFO tabella|0|DESCRIBE mostra schema.",
            "Come rinomini tabella?|RENAME TABLE a TO b|ALTER a NAME b|MOVE a b|0|RENAME cambia nome.",
            "Come elimini indice?|DROP INDEX|REMOVE INDEX|DELETE INDEX|0|DROP INDEX rimuove."
        ],

        L3: [
            "Come crei tabella?|CREATE TABLE|MAKE TABLE|NEW TABLE|0|CREATE TABLE crea.",
            "Come definisci chiave primaria?|PRIMARY KEY|MAIN KEY|ID KEY|0|PRIMARY KEY identifica.",
            "Come definisci chiave esterna?|FOREIGN KEY|LINK KEY|OUT KEY|0|FOREIGN collega.",
            "Come modifichi colonna?|ALTER TABLE|CHANGE TABLE|EDIT TABLE|0|ALTER modifica.",
            "Come aggiungi colonna?|ADD COLUMN|NEW COLUMN|INSERT COLUMN|0|ADD COLUMN aggiunge.",
            "Primary key auto?|PRIMARY KEY AUTO_INCREMENT|ID|KEY|0|PK auto.",
"Composite PK?|PRIMARY KEY(a,b)|MULTI|JOIN|0|PK composto.",
"FK reference?|REFERENCES t(id)|LINK|JOIN|0|FK.",
"ON DELETE CASCADE?|CASCADE|DELETE ALL|AUTO|0|Cascata.",
"ON UPDATE CASCADE?|CASCADE|UPDATE ALL|AUTO|0|Update cascata.",
"Check constraint?|CHECK(a>0)|VERIFY|TEST|0|Vincolo.",
"Enum?|ENUM('a','b')|SET|LIST|0|Valori fissi.",
"Set?|SET('a','b')|ENUM|LIST|0|Multi valore.",
"Default now?|DEFAULT CURRENT_TIMESTAMP|NOW|AUTO|0|Default time.",
"Index BTREE?|BTREE|HASH|TREE|0|Default.",
"Index HASH?|HASH|BTREE|MAP|0|Hash index.",
"Fulltext?|FULLTEXT|TEXT INDEX|SEARCH|0|Ricerca testo.",
"Show indexes?|SHOW INDEX|DESCRIBE|INFO|0|Indici.",
"Show tables?|SHOW TABLES|LIST|INFO|0|Tabelle.",
"Show create?|SHOW CREATE TABLE|DDL|INFO|0|DDL.",
"View updatable?|JOIN simple|Complex|NO|0|View update.",
"Materialized view?|Non supportata|YES|CACHE|0|MySQL no.",
"Temporary table?|CREATE TEMPORARY TABLE|TEMP|MEM|0|Temporanea.",
"Lock row?|SELECT ... FOR UPDATE|LOCK|BLOCK|0|Row lock.",
"Isolation level?|READ COMMITTED|LEVEL|MODE|0|Isolamento.",
"Read uncommitted?|READ UNCOMMITTED|DIRTY|FAST|0|Dirty read.",
"Repeatable read?|REPEATABLE READ|SAFE|LOCK|0|Default InnoDB.",
"Serializable?|SERIALIZABLE|STRICT|LOCK|0|Massimo.",
"Deadlock?|Conflitto lock|Crash|Error|0|Deadlock.",
"Show engine?|SHOW ENGINE INNODB STATUS|STATUS|INFO|0|Stato.",
"Explain analyze?|EXPLAIN ANALYZE|PLAN|DEBUG|0|Runtime.",
"Cost?|rows cost|time|size|0|Costo query.",
"Histogram?|ANALYZE TABLE|STATS|GRAPH|0|Distribuzione.",
"Partition?|PARTITION BY|SPLIT|SHARD|0|Partizioni.",

            // +5 nuove L3
            "Come imposti NOT NULL?|NOT NULL|NO NULL|REQUIRED|0|NOT NULL obbliga.",
            "Come imposti default?|DEFAULT 0|SET 0|AUTO 0|0|DEFAULT valore.",
            "Come auto increment?|AUTO_INCREMENT|AUTO|INCREMENT|0|AUTO_INCREMENT aumenta.",
            "Come vincolo unico?|UNIQUE|DISTINCT|ONLY|0|UNIQUE vincolo.",
            "Come elimina tabella?|DROP TABLE|DELETE TABLE|REMOVE TABLE|0|DROP elimina."
        ],

        L4: [
            "Come inizi transazione?|START TRANSACTION|BEGIN|OPEN TRANS|0|Avvia transazione.",
            "Come confermi?|COMMIT|SAVE|END|0|COMMIT salva.",
            "Come annulli?|ROLLBACK|UNDO|CANCEL|0|ROLLBACK annulla.",
            "Come crei vista?|CREATE VIEW|MAKE VIEW|NEW VIEW|0|VIEW salva query.",
            "Come fai trigger?|CREATE TRIGGER|NEW TRIGGER|ADD TRIGGER|0|TRIGGER evento.",
            "ACID?|Atomicità ecc|Index|Join|0|Transazioni.",
"Atomicità?|Tutto o nulla|Speed|Lock|0|Atomicità.",
"Consistenza?|Regole DB|Index|Join|0|Consistenza.",
"Isolamento?|Transazioni isolate|Thread|Lock|0|Isolamento.",
"Durabilità?|Persistenza|Backup|Cache|0|Durabilità.",
"Savepoint?|SAVEPOINT x|MARK|POINT|0|Punto ripristino.",
"Rollback to?|ROLLBACK TO x|UNDO|BACK|0|Rollback parziale.",
"Autocommit?|AUTOCOMMIT=0|OFF|STOP|0|Disabilita.",
"Lock tables?|LOCK TABLES|MUTEX|BLOCK|0|Lock manuale.",
"Unlock?|UNLOCK TABLES|FREE|OPEN|0|Sblocca.",
"Metadata lock?|DDL lock|Table lock|Row lock|0|MDL.",
"Gap lock?|Range lock|Row lock|None|0|InnoDB.",
"Next-key lock?|Row+gap|Index|None|0|InnoDB.",
"Phantom read?|Nuove righe|Dirty|Lost|0|Fenomeno.",
"Optimizer?|Query optimizer|Parser|Engine|0|Ottimizza.",
"Join order?|Optimizer decide|User|Index|0|Ordine join.",
"Covering index?|Index soddisfa|Join|Cache|0|Copre query.",
"Index selectivity?|Distribuzione valori|Size|Speed|0|Qualità.",
"Execution plan?|EXPLAIN|PLAN|RUN|0|Piano.",
"Cost based?|Costo stimato|Rule|Static|0|Optimizer.",
"Prepared statement?|Query preparata|Cache|View|0|Precompile.",
"SQL injection?|Input malevolo|Bug|Crash|0|Sicurezza.",
"Escape param?|Prepared stmt|Concat|Replace|0|Sicuro.",
"Stored function?|RETURN valore|Procedure|Trigger|0|Funzione.",
"Deterministic?|Stesso input|Random|Time|0|Deterministica.",
"Trigger BEFORE?|BEFORE INSERT|AFTER|ON|0|Prima evento.",
"Trigger AFTER?|AFTER UPDATE|BEFORE|ON|0|Dopo evento.",
"Event scheduler?|CREATE EVENT|CRON|JOB|0|Task schedulati.",
"Replication?|Master-slave|Backup|Cluster|0|Replica.",
"Backup?|mysqldump|EXPORT|SAVE|0|Backup logico.",

            // +5 nuove L4
            "Come fai stored procedure?|CREATE PROCEDURE|MAKE PROC|NEW PROC|0|Procedure SQL.",
            "Come chiami procedure?|CALL proc()|RUN proc()|EXEC proc()|0|CALL esegue.",
            "Come usi IF?|IF(cond, a, b)|CASE|WHEN|0|IF condizionale.",
            "Come usi CASE?|CASE WHEN THEN END|IF ELSE|SWITCH|0|CASE multiplo.",
            "Come blocchi tabella?|LOCK TABLES|FREEZE|MUTEX|0|LOCK blocca."
        ]
    },
    HTML: {
        L1: [
            "Cos'è HTML?|Un linguaggio di markup|Un linguaggio di programmazione|Un database|0|HTML struttura pagine.",
            "Quale tag crea un titolo?|<h1>|<p>|<title>|0|h1 è titolo.",
            "Quale tag crea paragrafo?|<p>|<div>|<span>|0|p è paragrafo.",
            "Come crei link?|<a href='url'>|<link>|<url>|0|a crea link.",
            "Come inserisci immagine?|<img src='img'>|<image>|<pic>|0|img mostra immagini.",
            "Tag radice HTML?|<html>|<body>|<head>|0|html è radice.",
"Dove va il testo?|<body>|<head>|<html>|0|body contiene contenuto.",
"Dove vanno meta?|<head>|<body>|<meta>|0|head contiene meta.",
"Tag titolo pagina?|<title>|<h1>|<head>|0|title è titolo browser.",
"Tag commento?|<!-- -->|//|#|0|Commento HTML.",
"Tag corsivo?|<i>|<b>|<em>|0|i corsivo.",
"Tag grassetto?|<b>|<strong>|<bold>|0|b grassetto.",
"Tag enfasi?|<em>|<i>|<b>|0|em enfasi.",
"Tag forte?|<strong>|<b>|<em>|0|strong semantico.",
"Tag citazione?|<blockquote>|<quote>|<q>|0|blockquote citazione.",
"Tag citazione breve?|<q>|<blockquote>|<cite>|0|q inline.",
"Tag codice?|<code>|<pre>|<kbd>|0|code inline.",
"Tag preformattato?|<pre>|<code>|<p>|0|pre mantiene spazi.",
"Tag lista definizione?|<dl>|<ul>|<ol>|0|dl definizione.",
"Termine definizione?|<dt>|<dd>|<li>|0|dt termine.",
"Descrizione?|<dd>|<dt>|<li>|0|dd descrizione.",
"Tag tabella?|<table>|<tab>|<grid>|0|table struttura.",
"Riga tabella?|<tr>|<td>|<th>|0|tr riga.",
"Cella tabella?|<td>|<tr>|<th>|0|td cella.",
"Intestazione tabella?|<th>|<td>|<tr>|0|th header.",
"Tag link vuoto?|<a>|<link>|<url>|0|a link.",
"Attributo link?|href|src|url|0|href destinazione.",
"Target nuova tab?|target='_blank'|new tab|blank|0|Apre nuova.",
"Tag immagine?|<img>|<picture>|<src>|0|img immagine.",
"Attributo immagine?|src|href|link|0|src sorgente.",
"Testo alternativo?|alt|title|name|0|alt accessibilità.",
"Tag audio?|<audio>|<sound>|<media>|0|audio HTML5.",
"Tag video?|<video>|<movie>|<media>|0|video HTML5.",
"Autoplay?|autoplay|auto|play|0|Riproduzione auto.",
"Controlli media?|controls|ui|panel|0|Controls visibili.",

            // +5 nuove L1
            "Quale tag lista non ordinata?|<ul>|<ol>|<li>|0|ul lista puntata.",
            "Quale tag lista ordinata?|<ol>|<ul>|<li>|0|ol numerata.",
            "Quale tag elemento lista?|<li>|<ul>|<ol>|0|li elemento.",
            "Quale tag va a capo?|<br>|<hr>|<lb>|0|br va a capo.",
            "Quale tag linea orizzontale?|<hr>|<br>|<line>|0|hr linea."
        ],

        L2: [
            "Cos'è un attributo?|Info extra tag|Tag speciale|Valore CSS|0|Attributo estende tag.",
            "Come aggiungi classe?|class='x'|id='x'|style='x'|0|class assegna classe.",
            "Come aggiungi id?|id='x'|class='x'|name='x'|0|id identifica.",
            "Come commenti HTML?|<!-- -->|//|#|0|Commento HTML.",
            "Come includi CSS?|<link>|<style>|<css>|0|link collega CSS.",
            "Attributo style?|style='...'|css|class|0|Style inline.",
"Multipli class?|class='a b'|class='a,b'|multi|0|Spazi separano.",
"Attributo name?|name='x'|id='x'|key|0|name form.",
"Input password?|type='password'|text|secret|0|Campo password.",
"Input number?|type='number'|int|digit|0|Numero.",
"Input email?|type='email'|mail|text|0|Email.",
"Input radio?|type='radio'|check|select|0|Radio button.",
"Input submit?|type='submit'|send|button|0|Invia form.",
"Label?|<label>|<name>|<tag>|0|Label campo.",
"For label?|for='id'|name|bind|0|Associa input.",
"Textarea?|<textarea>|<input>|<text>|0|Testo lungo.",
"Select?|<select>|<option>|<list>|0|Menu.",
"Option?|<option>|<item>|<li>|0|Opzione.",
"Selected?|selected|checked|active|0|Opzione default.",
"Disabled?|disabled|readonly|off|0|Disabilita.",
"Readonly?|readonly|disabled|lock|0|Solo lettura.",
"Required?|required|mandatory|must|0|Obbligatorio.",
"Placeholder?|placeholder|hint|text|0|Suggerimento.",
"Maxlength?|maxlength|max|limit|0|Limite testo.",
"Form action?|action='url'|method|target|0|Destinazione.",
"Form method?|method='post'|get|send|0|Metodo invio.",
"GET?|method='get'|post|fetch|0|Param URL.",
"POST?|method='post'|get|push|0|Dati nel body.",
"Fieldset?|<fieldset>|<group>|<box>|0|Gruppo campi.",
"Legend?|<legend>|<title>|<label>|0|Titolo fieldset.",
"Button type?|type='button'|click|action|0|Bottone neutro.",
"Reset?|type='reset'|clear|undo|0|Reset form.",
"Autocomplete?|autocomplete='off'|disable|none|0|Auto compilazione.",
"Pattern?|pattern='[0-9]'|regex|mask|0|Validazione.",
"Hidden?|type='hidden'|invisible|none|0|Campo nascosto.",

            // +5 nuove L2
            "Come includi JS?|<script>|<js>|<code>|0|script carica JS.",
            "Come input testo?|<input type='text'>|<text>|<input>|0|input testo.",
            "Come checkbox?|<input type='checkbox'>|<check>|<box>|0|checkbox.",
            "Come bottone?|<button>|<btn>|<click>|0|button cliccabile.",
            "Come form?|<form>|<input>|<data>|0|form invia dati."
        ],

        L3: [
            "Cos'è un div?|Contenitore|Testo|Immagine|0|div è contenitore.",
            "Cos'è span?|Inline|Blocco|Lista|0|span inline.",
            "Cos'è semantico?|Tag con significato|Solo stile|Solo JS|0|Semantica aiuta.",
            "Quale è header?|<header>|<top>|<head>|0|header semantico.",
            "Quale è footer?|<footer>|<bottom>|<end>|0|footer semantico.",
            "Tag header?|<header>|<top>|<head>|0|Header semantico.",
"Tag footer?|<footer>|<bottom>|<end>|0|Footer semantico.",
"Tag main?|<main>|<body>|<content>|0|Main contenuto.",
"Tag nav?|<nav>|<menu>|<ul>|0|Navigazione.",
"Tag section?|<section>|<div>|<part>|0|Sezione.",
"Tag article?|<article>|<post>|<div>|0|Articolo.",
"Tag aside?|<aside>|<side>|<extra>|0|Laterale.",
"Figure?|<figure>|<img>|<media>|0|Contenitore media.",
"Figcaption?|<figcaption>|<caption>|<title>|0|Descrizione figura.",
"Time?|<time>|<date>|<span>|0|Data/ora.",
"Mark?|<mark>|<highlight>|<em>|0|Evidenzia.",
"Details?|<details>|<info>|<box>|0|Espandibile.",
"Summary?|<summary>|<title>|<header>|0|Titolo details.",
"Progress?|<progress>|<bar>|<meter>|0|Progresso.",
"Meter?|<meter>|<progress>|<bar>|0|Valore misurato.",
"Address?|<address>|<contact>|<info>|0|Contatti.",
"Data attr?|data-x|attr-x|custom|0|Custom data.",
"Uso data attr?|JS/CSS|SEO|Meta|0|Dati custom.",
"Role?|role='button'|type|class|0|ARIA role.",
"Tabindex?|tabindex='0'|focus|order|0|Navigazione tastiera.",
"Hidden attr?|hidden|display:none|invisible|0|Nasconde elemento.",
"Contenteditable?|contenteditable|edit|write|0|Editabile.",
"Draggable?|draggable|move|drag|0|Trascinabile.",
"Spellcheck?|spellcheck|grammar|check|0|Controllo testo.",
"Lang?|lang='it'|language|locale|0|Lingua.",
"Dir?|dir='rtl'|align|right|0|Direzione testo.",
"Title attr?|title='...'|tooltip|hint|0|Tooltip.",
"Rel?|rel='noopener'|link|ref|0|Relazione.",
"Download?|download|save|file|0|Forza download.",
"Sandbox?|sandbox|secure|lock|0|Iframe sicurezza.",

            // +5 nuove L3
            "Quale è nav?|<nav>|<menu>|<link>|0|nav navigazione.",
            "Quale è section?|<section>|<div>|<part>|0|section sezione.",
            "Quale è article?|<article>|<post>|<blog>|0|article contenuto.",
            "Quale è main?|<main>|<body>|<content>|0|main principale.",
            "Quale è aside?|<aside>|<side>|<extra>|0|aside laterale."
        ],

        L4: [
            "Cos'è DOCTYPE?|Dichiara HTML|Tag visivo|Script|0|DOCTYPE standard.",
            "Cos'è accessibilità?|Usabile per tutti|Solo disabili|Solo SEO|0|Accessibilità inclusiva.",
            "Cos'è SEO?|Ottimizzazione motori|Grafica|JS|0|SEO migliora ranking.",
            "Cos'è responsive?|Adattabile|Veloce|Statico|0|Responsive si adatta.",
            "Cos'è meta viewport?|Controllo layout|Titolo|Script|0|Viewport gestisce scala.",
            "DOCTYPE html5?|<!DOCTYPE html>|<!HTML>|<!DOCTYPE>|0|Standard HTML5.",
"Rendering mode?|Standards|Quirks|Legacy|0|Modalità browser.",
"Validatore HTML?|W3C Validator|SEO|Lint|0|Verifica codice.",
"Accessibilità?|WCAG|ARIA|SEO|0|Linee guida.",
"WCAG?|Standard accessibilità|SEO|JS|0|Linee guida.",
"ARIA label?|aria-label|alt|title|0|Testo screen reader.",
"ARIA hidden?|aria-hidden='true'|hidden|display|0|Nasconde SR.",
"Role button?|role='button'|type|class|0|Semantica ARIA.",
"Tab order?|tabindex|order|index|0|Ordine focus.",
"Focus visible?|:focus-visible|hover|active|0|Stato focus.",
"Lazy image?|loading='lazy'|delay|async|0|Lazy loading.",
"Async script?|async|defer|lazy|0|Caricamento async.",
"Defer script?|defer|async|wait|0|Dopo parsing.",
"Async vs defer?|Ordine esecuzione|Velocità|CSS|0|Differenza.",
"SEO on-page?|Tag semantici|JS|CSS|0|SEO base.",
"Meta description?|<meta name='description'>|title|keywords|0|Descrizione.",
"Meta charset?|<meta charset='utf-8'>|lang|encode|0|Encoding.",
"Viewport?|<meta viewport>|layout|scale|0|Responsive.",
"Mobile first?|Design mobile|Desktop|Fixed|0|Approccio.",
"Responsive img?|srcset|resize|scale|0|Immagini responsive.",
"Picture?|<picture>|<img>|<media>|0|Immagini adattive.",
"Iframe?|<iframe>|<frame>|<embed>|0|Contenuto esterno.",
"Sandbox iframe?|sandbox|secure|lock|0|Isolamento.",
"CORS?|Cross origin|Security|SEO|0|Policy browser.",
"Preload?|<link rel='preload'>|load|cache|0|Precarica.",
"Prefetch?|prefetch|preload|cache|0|Anticipa.",
"Critical CSS?|Above the fold|Inline|All|0|CSS critico.",
"HTML template?|<template>|<slot>|<layout>|0|Template.",
"Slot?|<slot>|<placeholder>|<fill>|0|Web component.",
"Custom element?|<my-tag>|<div>|<component>|0|Web component.",
"Shadow DOM?|Isolamento DOM|CSS|JS|0|Incapsulamento.",

            // +5 nuove L4
            "Cos'è ARIA?|Attributi accessibilità|CSS|JS|0|ARIA aiuta screen reader.",
            "Cos'è lazy loading?|Carica dopo|Carica tutto|Cache|0|Lazy carica tardi.",
            "Cos'è semantic HTML?|Tag significativi|Solo div|CSS|0|Semantica chiara.",
            "Cos'è web standard?|Regole W3C|Framework|Browser|0|Standard comuni.",
            "Cos'è validazione HTML?|Controllo errori|Design|SEO|0|Validazione verifica."
        ]
    }
};

const challenges5 = {
    Python: [
        { task: "Conta da 1 a 3", logic: "for i in range(1, 4)", output: "1\n2\n3", userStatus: null },
        { task: "Stampa numeri pari fino a 6", logic: "for i in range(2,7,2)", output: "2\n4\n6", userStatus: null },
        { task: "Somma numeri da 1 a 5", logic: "sum(range(1,6))", output: "15", userStatus: null },
        { task: "Crea una lista di quadrati 1-5", logic: "[i*i for i in range(1,6)]", output: "[1, 4, 9, 16, 25]", userStatus: null },
        { task: "Stampa 'Ciao' 3 volte usando ciclo", logic: "for i in range(3): print('Ciao')", output: "Ciao\nCiao\nCiao", userStatus: null },
        { task: "Stampa numeri 1-10", logic: "for i in range(1,11): print(i)", output: "1\2\3\4\5\6\7\8\9\10", userStatus: null },
{ task: "Somma numeri pari 1-10", logic: "sum(i for i in range(1,11) if i%2==0)", output: "30", userStatus: null },
{ task: "Crea lista dispari 1-10", logic: "[i for i in range(1,11) if i%2!=0]", output: "[1,3,5,7,9]", userStatus: null },
{ task: "Max lista [3,7,2]", logic: "max([3,7,2])", output: "7", userStatus: null },
{ task: "Min lista [3,7,2]", logic: "min([3,7,2])", output: "2", userStatus: null },
{ task: "Ordina lista [3,1,2]", logic: "sorted([3,1,2])", output: "[1,2,3]", userStatus: null },
{ task: "Conta elementi lista", logic: "len([1,2,3,4])", output: "4", userStatus: null },
{ task: "Controlla se 3 in lista", logic: "3 in [1,2,3]", output: "True", userStatus: null },
{ task: "Unisci liste [1,2] e [3]", logic: "[1,2]+[3]", output: "[1,2,3]", userStatus: null },
{ task: "Stampa chiavi dict", logic: "list({'a':1,'b':2}.keys())", output: "['a','b']", userStatus: null },
{ task: "Stampa valori dict", logic: "list({'a':1,'b':2}.values())", output: "[1,2]", userStatus: null },
{ task: "Uppercase stringa", logic: "'ciao'.upper()", output: "CIAO", userStatus: null },
{ task: "Lowercase stringa", logic: "'CIAO'.lower()", output: "ciao", userStatus: null },
{ task: "Replace stringa", logic: "'ciao'.replace('a','o')", output: "cioo", userStatus: null },
{ task: "Split stringa", logic: "'a,b,c'.split(',')", output: "['a','b','c']", userStatus: null },
{ task: "Join lista", logic: "','.join(['a','b'])", output: "a,b", userStatus: null },
{ task: "Controllo if semplice", logic: "if 5>3: print('ok')", output: "ok", userStatus: null },
{ task: "While 1-3", logic: "i=1\nwhile i<=3: print(i); i+=1", output: "1\n2\n3", userStatus: null },
{ task: "Funzione somma", logic: "def f(a,b): return a+b", output: "funzione", userStatus: null },
{ task: "Lambda x2", logic: "lambda x: x*2", output: "funzione", userStatus: null },
        { task: "Stampa numeri da 5 a 1", logic: "for i in range(5,0,-1)", output: "5\n4\n3\n2\n1", userStatus: null },
        { task: "Crea lista con valori doppi di 1-5", logic: "[i*2 for i in range(1,6)]", output: "[2, 4, 6, 8, 10]", userStatus: null },
        { task: "Conta caratteri in 'Python'", logic: "len('Python')", output: "6", userStatus: null },
        { task: "Somma elementi lista [1,2,3,4]", logic: "sum([1,2,3,4])", output: "10", userStatus: null },
        { task: "Crea dizionario da lista [1,2,3]", logic: "{i:i*i for i in [1,2,3]}", output: "{1: 1, 2: 4, 3: 9}", userStatus: null }
    ],
    JavaScript: [
        { task: "Conta da 1 a 5", logic: "for(let i=1;i<=5;i++)", output: "1\n2\n3\n4\n5", userStatus: null },
        { task: "Ciclo su array [1,2,3]", logic: "for(let x of [1,2,3])", output: "1\n2\n3", userStatus: null },
        { task: "Somma numeri da 1 a 5", logic: "let sum=0;for(let i=1;i<=5;i++)", output: "15", userStatus: null },
        { task: "Stampa solo numeri pari 1-10", logic: "for(let i=2;i<=10;i+=2)", output: "2\n4\n6\n8\n10", userStatus: null },
        { task: "Crea array di quadrati 1-5", logic: "[1,2,3,4,5].map(x=>x*x)", output: "[1,4,9,16,25]", userStatus: null },
        { task: "Conta 1-10", logic: "for(let i=1;i<=10;i++)", output: "1\n2\n3\n4\n5\n6\n7\n8\n9\n10", userStatus: null },
{ task: "While 1-3", logic: "let i=1;while(i<=3){i++;}", output: "1\n2\n3", userStatus: null },
{ task: "Somma array", logic: "[1,2,3].reduce((a,b)=>a+b)", output: "6", userStatus: null },
{ task: "Max array", logic: "Math.max(...[1,5,2])", output: "5", userStatus: null },
{ task: "Min array", logic: "Math.min(...[1,5,2])", output: "1", userStatus: null },
{ task: "Lunghezza array", logic: "[1,2,3].length", output: "3", userStatus: null },
{ task: "Include valore", logic: "[1,2,3].includes(2)", output: "true", userStatus: null },
{ task: "Concat array", logic: "[1,2].concat([3])", output: "[1,2,3]", userStatus: null },
{ task: "Uppercase stringa", logic: "'ciao'.toUpperCase()", output: "CIAO", userStatus: null },
{ task: "Lowercase stringa", logic: "'CIAO'.toLowerCase()", output: "ciao", userStatus: null },
{ task: "Split stringa", logic: "'a,b'.split(',')", output: "['a','b']", userStatus: null },
{ task: "Join array", logic: "['a','b'].join(',')", output: "a,b", userStatus: null },
{ task: "If semplice", logic: "if(5>3) console.log('ok')", output: "ok", userStatus: null },
{ task: "Arrow function", logic: "x=>x*2", output: "funzione", userStatus: null },
{ task: "Push array", logic: "arr.push(4)", output: "OK", userStatus: null },
{ task: "Pop array", logic: "arr.pop()", output: "OK", userStatus: null },
{ task: "Shift array", logic: "arr.shift()", output: "OK", userStatus: null },
{ task: "Unshift array", logic: "arr.unshift(1)", output: "OK", userStatus: null },
{ task: "Object key", logic: "Object.keys({a:1})", output: "['a']", userStatus: null },
{ task: "Object value", logic: "Object.values({a:1})", output: "[1]", userStatus: null },
        { task: "Conta da 10 a 1", logic: "for(let i=10;i>=1;i--)", output: "10\n9\n8\n7\n6\n5\n4\n3\n2\n1", userStatus: null },
        { task: "Somma elementi array [5,10,15]", logic: "[5,10,15].reduce((a,b)=>a+b,0)", output: "30", userStatus: null },
        { task: "Stampa 'JS' 4 volte", logic: "for(let i=0;i<4;i++) console.log('JS')", output: "JS\nJS\nJS\nJS", userStatus: null },
        { task: "Crea array con valori doppi [1,2,3]", logic: "[1,2,3].map(x=>x*2)", output: "[2,4,6]", userStatus: null },
        { task: "Filtra numeri pari da [1,2,3,4,5]", logic: "[1,2,3,4,5].filter(x=>x%2===0)", output: "[2,4]", userStatus: null }
    ],
    Java: [
        { task: "Main che stampa 'Ciao'", logic: "System.out.println(\"Ciao\")", output: "Ciao", userStatus: null },
        { task: "Conta da 1 a 3", logic: "for(int i=1;i<=3;i++)", output: "1\n2\n3", userStatus: null },
        { task: "Somma numeri 1-5", logic: "int sum=0;for(int i=1;i<=5;i++)", output: "15", userStatus: null },
        { task: "Stampa numeri pari 1-6", logic: "for(int i=2;i<=6;i+=2)", output: "2\n4\n6", userStatus: null },
        { task: "If semplice", logic: "if(5>3) System.out.println(\"ok\");", output: "ok", userStatus: null },
{ task: "While 1-3", logic: "int i=1;while(i<=3){i++;}", output: "1\n2\n3", userStatus: null },
        { task: "Array length", logic: "int[] a={1,2}; a.length", output: "2", userStatus: null },
{ task: "Max tra due numeri", logic: "Math.max(3,5)", output: "5", userStatus: null },
{ task: "Min tra due numeri", logic: "Math.min(3,5)", output: "3", userStatus: null },
{ task: "String length", logic: "\"ciao\".length()", output: "4", userStatus: null },
{ task: "Uppercase stringa", logic: "\"ciao\".toUpperCase()", output: "CIAO", userStatus: null },
{ task: "Lowercase stringa", logic: "\"CIAO\".toLowerCase()", output: "ciao", userStatus: null },
        { task: "Somma array {1,2,3}", logic: "int[] a={1,2,3}; int s=0; for(int x:a) s+=x;", output: "6", userStatus: null },
        { task: "For each su {1,2}", logic: "for(int x: new int[]{1,2})", output: "loop", userStatus: null },
{ task: "Boolean true", logic: "boolean x=true;", output: "true", userStatus: null },
{ task: "Confronto ==", logic: "a==b", output: "boolean", userStatus: null },
{ task: "Confronto !=", logic: "a!=b", output: "boolean", userStatus: null },
{ task: "Incremento", logic: "i++", output: "numero", userStatus: null },
{ task: "Decremento", logic: "i--", output: "numero", userStatus: null },
{ task: "Array init", logic: "int[] a={1,2,3};", output: "[1,2,3]", userStatus: null },
{ task: "Stampa array", logic: "Arrays.toString(a)", output: "[1,2,3]", userStatus: null },
{ task: "Import Arrays", logic: "import java.util.Arrays;", output: "OK", userStatus: null },
{ task: "Metodo statico", logic: "static void f(){}", output: "OK", userStatus: null },
{ task: "Return int", logic: "return 5;", output: "5", userStatus: null },
        { task: "Conta da 5 a 1", logic: "for(int i=5;i>=1;i--)", output: "5\n4\n3\n2\n1", userStatus: null },
        { task: "Crea array di quadrati [1-5]", logic: "int[] squares = {1,4,9,16,25};", output: "[1,4,9,16,25]", userStatus: null },
        { task: "Somma array [1,2,3,4]", logic: "int sum=0;for(int i: new int[]{1,2,3,4}) sum+=i;", output: "10", userStatus: null },
        { task: "Stampa 'Hello' 3 volte", logic: "for(int i=0;i<3;i++) System.out.println(\"Hello\");", output: "Hello\nHello\nHello", userStatus: null },
        { task: "Conta numeri dispari 1-5", logic: "for(int i=1;i<=5;i+=2)", output: "1\n3\n5", userStatus: null }
    ],
    MySQL: [
        { task: "Seleziona tutti da tabella utenti", logic: "SELECT * FROM utenti", output: "OK", userStatus: null },
        { task: "Conta record tabella prodotti", logic: "SELECT COUNT(*) FROM prodotti", output: "OK", userStatus: null },
        { task: "Seleziona nome e prezzo da prodotti", logic: "SELECT nome, prezzo FROM prodotti", output: "OK", userStatus: null },
        { task: "Seleziona prodotti con prezzo > 100", logic: "SELECT * FROM prodotti WHERE prezzo>100", output: "OK", userStatus: null },
        { task: "Conta utenti", logic: "SELECT COUNT(*) FROM utenti", output: "OK", userStatus: null },
{ task: "Somma prezzi", logic: "SELECT SUM(prezzo) FROM prodotti", output: "OK", userStatus: null },
{ task: "Prezzo medio", logic: "SELECT AVG(prezzo) FROM prodotti", output: "OK", userStatus: null },
{ task: "Prezzo max", logic: "SELECT MAX(prezzo) FROM prodotti", output: "OK", userStatus: null },
{ task: "Prezzo min", logic: "SELECT MIN(prezzo) FROM prodotti", output: "OK", userStatus: null },
{ task: "Group by categoria", logic: "SELECT categoria,COUNT(*) FROM prodotti GROUP BY categoria", output: "OK", userStatus: null },
{ task: "Having", logic: "HAVING COUNT(*)>1", output: "OK", userStatus: null },
{ task: "Alias colonna", logic: "SELECT prezzo AS p FROM prodotti", output: "OK", userStatus: null },
{ task: "Like", logic: "SELECT * FROM utenti WHERE nome LIKE 'A%'", output: "OK", userStatus: null },
{ task: "In", logic: "SELECT * FROM prodotti WHERE id IN (1,2)", output: "OK", userStatus: null },
{ task: "Not in", logic: "NOT IN (1,2)", output: "OK", userStatus: null },
{ task: "Is null", logic: "WHERE email IS NULL", output: "OK", userStatus: null },
{ task: "Is not null", logic: "WHERE email IS NOT NULL", output: "OK", userStatus: null },
{ task: "Limit offset", logic: "LIMIT 5 OFFSET 5", output: "OK", userStatus: null },
{ task: "Order desc", logic: "ORDER BY prezzo DESC", output: "OK", userStatus: null },
{ task: "Between date", logic: "BETWEEN '2023-01-01' AND '2023-12-31'", output: "OK", userStatus: null },
{ task: "Delete where", logic: "DELETE FROM utenti WHERE id=1", output: "OK", userStatus: null },
{ task: "Update where", logic: "UPDATE utenti SET nome='x' WHERE id=1", output: "OK", userStatus: null },
{ task: "Insert", logic: "INSERT INTO utenti(nome) VALUES('a')", output: "OK", userStatus: null },
{ task: "Create table", logic: "CREATE TABLE test(id INT)", output: "OK", userStatus: null },
        { task: "Seleziona utenti con età > 18", logic: "SELECT * FROM utenti WHERE eta>18", output: "OK", userStatus: null },
        { task: "Seleziona nomi distinct", logic: "SELECT DISTINCT nome FROM utenti", output: "OK", userStatus: null },
        { task: "Ordina utenti per nome", logic: "SELECT * FROM utenti ORDER BY nome", output: "OK", userStatus: null },
        { task: "Seleziona primi 3 prodotti", logic: "SELECT * FROM prodotti LIMIT 3", output: "OK", userStatus: null },
        { task: "Seleziona prodotti prezzo tra 50 e 100", logic: "SELECT * FROM prodotti WHERE prezzo BETWEEN 50 AND 100", output: "OK", userStatus: null }
    ],
    HTML: [
        { task: "Crea un div", logic: "<div>", output: "OK", userStatus: null },
        { task: "Crea un paragrafo", logic: "<p>", output: "OK", userStatus: null },
        { task: "Crea un link", logic: "<a href=''>", output: "OK", userStatus: null },
        { task: "Crea un'immagine", logic: "<img src=''>", output: "OK", userStatus: null },
        { task: "Crea span", logic: "<span>", output: "OK", userStatus: null },
{ task: "Crea strong", logic: "<strong>", output: "OK", userStatus: null },
{ task: "Crea em", logic: "<em>", output: "OK", userStatus: null },
{ task: "Crea form", logic: "<form>", output: "OK", userStatus: null },
{ task: "Crea label", logic: "<label>", output: "OK", userStatus: null },
{ task: "Crea textarea", logic: "<textarea>", output: "OK", userStatus: null },
{ task: "Crea select", logic: "<select>", output: "OK", userStatus: null },
{ task: "Crea option", logic: "<option>", output: "OK", userStatus: null },
{ task: "Crea table", logic: "<table>", output: "OK", userStatus: null },
{ task: "Crea tr", logic: "<tr>", output: "OK", userStatus: null },
{ task: "Crea td", logic: "<td>", output: "OK", userStatus: null },
{ task: "Crea th", logic: "<th>", output: "OK", userStatus: null },
{ task: "Crea header", logic: "<header>", output: "OK", userStatus: null },
{ task: "Crea footer", logic: "<footer>", output: "OK", userStatus: null },
{ task: "Crea nav", logic: "<nav>", output: "OK", userStatus: null },
{ task: "Crea section", logic: "<section>", output: "OK", userStatus: null },
{ task: "Crea article", logic: "<article>", output: "OK", userStatus: null },
{ task: "Crea main", logic: "<main>", output: "OK", userStatus: null },
{ task: "Crea iframe", logic: "<iframe>", output: "OK", userStatus: null },
{ task: "Crea video", logic: "<video controls>", output: "OK", userStatus: null },
        { task: "Crea una lista non ordinata", logic: "<ul>", output: "OK", userStatus: null },
        { task: "Crea lista ordinata", logic: "<ol>", output: "OK", userStatus: null },
        { task: "Crea un header h1", logic: "<h1>", output: "OK", userStatus: null },
        { task: "Crea un bottone", logic: "<button>", output: "OK", userStatus: null },
        { task: "Crea un input text", logic: "<input type='text'>", output: "OK", userStatus: null }
    ]
};
